import type { VNodeChild } from 'vue'
import type { VueRefTarget } from '@mantine-vue/hooks'
import type {
  BoxMod,
  BoxProps,
  MantineColor,
  MantineGradient,
  MantineRadius,
  MantineSize,
  StylesApiProps,
  PolymorphicFactory,
  MantineElementType,
} from '../../core'
import type { AvatarGroup } from './AvatarGroup/AvatarGroup'

export type AvatarVariant =
  | 'filled'
  | 'light'
  | 'gradient'
  | 'outline'
  | 'transparent'
  | 'default'
  | 'white'

/** Props declared by `Avatar` itself. See `AvatarProps` for the full public type. */
export interface AvatarOwnProps extends StylesApiProps<AvatarProps> {
  /** Receives the root DOM node. The factory narrows this to the element the selected root renders. */
  rootRef?: VueRefTarget<Element>

  /**
   * Root element or component rendered by `Avatar`.
   *
   * @default 'div'
   */
  component?: MantineElementType

  /**
   * Width and height of the avatar, numbers are converted to rem
   *
   * @default 'md'
   */
  size?: MantineSize | (string & {}) | number

  /**
   * Key of `theme.radius` or any valid CSS value to set border-radius
   *
   * @default '1000px'
   */
  radius?: MantineRadius

  /**
   * Key of `theme.colors` or any valid CSS color
   *
   * @default 'gray'
   */
  color?: MantineColor | 'initials'

  /**
   * Gradient configuration for `variant="gradient"`
   *
   * @default theme.defaultGradient
   */
  gradient?: MantineGradient

  /** Image url, if the image cannot be loaded or `src={null}`, then placeholder is displayed instead */
  src?: string | null

  /** Image `alt` attribute, also used as `title` attribute for placeholder */
  alt?: string

  /** Attributes passed down to `img` element */
  imageProps?: Record<string, any>

  /** If set, adjusts text color based on background color for `filled` variant */
  autoContrast?: boolean

  /** Name of the user. When `src` is not set, used to display initials and to generate color when `color="initials"` is set. */
  name?: string

  /** A list of colors that is used for autogenerated initials. By default, all default Mantine colors can be used except gray and dark. */
  allowedInitialsColors?: MantineColor[]

  /** Controls visual representation of the component. Rendered as the `data-variant` attribute and passed to the Styles API. */
  variant?: AvatarVariant

  /** Element modifiers transformed into `data-` attributes, for example, `{ 'data-size': 'xl' }`, falsy values are removed */
  mod?: BoxMod
}

export interface AvatarProps extends Omit<BoxProps, keyof AvatarOwnProps>, AvatarOwnProps {}

export interface AvatarSlots {
  default?: () => VNodeChild
}
export type AvatarStylesNames = 'root' | 'placeholder' | 'image'
export type AvatarCssVariables = {
  root: '--avatar-size' | '--avatar-radius' | '--avatar-bg' | '--avatar-color' | '--avatar-bd'
}

/** Public contract of `Avatar`. `component` and `rootRef` come from the factory. */
export type AvatarFactory = PolymorphicFactory<{
  props: Omit<AvatarProps, 'component' | 'rootRef'>
  slots: AvatarSlots
  ref: HTMLDivElement
  exposed: { rootElement: Element | null }
  defaultComponent: 'div'
  defaultRef: HTMLDivElement
  stylesNames: AvatarStylesNames
  vars: AvatarCssVariables
  variant: AvatarVariant
  staticComponents: {
    Group: typeof AvatarGroup
  }
}>
