export { ModalBase } from './ModalBase'
export { ModalBaseBody } from './ModalBaseBody'
export { ModalBaseCloseButton } from './ModalBaseCloseButton'
export { ModalBaseContent } from './ModalBaseContent'
export { ModalBaseHeader } from './ModalBaseHeader'
export { ModalBaseOverlay } from './ModalBaseOverlay'
export { ModalBaseTitle } from './ModalBaseTitle'
export * from './NativeScrollArea'
export type { ModalBaseOwnProps, ModalBaseProps, ModalBaseSlots } from './ModalBase'
export type { ModalBaseBodyProps, ModalBaseBodySlots } from './ModalBaseBody'
export type { ModalBaseCloseButtonProps, ModalBaseCloseButtonSlots } from './ModalBaseCloseButton'
export type { ModalBaseContentProps } from './ModalBaseContent'
export type { ModalBaseHeaderProps, ModalBaseHeaderSlots } from './ModalBaseHeader'
export type { ModalBaseOverlayOwnProps, ModalBaseOverlayProps } from './ModalBaseOverlay'
export type { ModalBaseTitleProps, ModalBaseTitleSlots } from './ModalBaseTitle'
export type ModalBaseStylesNames =
  | 'body'
  | 'header'
  | 'title'
  | 'overlay'
  | 'root'
  | 'content'
  | 'close'
  | 'inner'
