export const elements = [
  { position: 6, mass: 12.011, symbol: 'C', name: 'Carbon' },
  { position: 7, mass: 14.007, symbol: 'N', name: 'Nitrogen' },
  { position: 39, mass: 88.906, symbol: 'Y', name: 'Yttrium' },
  { position: 56, mass: 137.33, symbol: 'Ba', name: 'Barium' },
  { position: 58, mass: 140.12, symbol: 'Ce', name: 'Cerium' },
]

export const elementsLong = [
  { position: 1, mass: 1.008, symbol: 'H', name: 'Hydrogen' },
  { position: 2, mass: 4.0026, symbol: 'He', name: 'Helium' },
  { position: 3, mass: 6.94, symbol: 'Li', name: 'Lithium' },
  { position: 4, mass: 9.0122, symbol: 'Be', name: 'Beryllium' },
  { position: 5, mass: 10.81, symbol: 'B', name: 'Boron' },
  { position: 6, mass: 12.011, symbol: 'C', name: 'Carbon' },
  { position: 7, mass: 14.007, symbol: 'N', name: 'Nitrogen' },
  { position: 8, mass: 15.999, symbol: 'O', name: 'Oxygen' },
  { position: 9, mass: 18.998, symbol: 'F', name: 'Fluorine' },
  { position: 10, mass: 20.18, symbol: 'Ne', name: 'Neon' },
  { position: 11, mass: 22.99, symbol: 'Na', name: 'Sodium' },
  { position: 12, mass: 24.305, symbol: 'Mg', name: 'Magnesium' },
  { position: 13, mass: 26.982, symbol: 'Al', name: 'Aluminium' },
  { position: 14, mass: 28.085, symbol: 'Si', name: 'Silicon' },
  { position: 15, mass: 30.974, symbol: 'P', name: 'Phosphorus' },
  { position: 16, mass: 32.06, symbol: 'S', name: 'Sulfur' },
  { position: 17, mass: 35.45, symbol: 'Cl', name: 'Chlorine' },
  { position: 18, mass: 39.948, symbol: 'Ar', name: 'Argon' },
  { position: 19, mass: 39.098, symbol: 'K', name: 'Potassium' },
  { position: 20, mass: 39.098, symbol: 'Ca', name: 'Calcium' },
]
