import type { Frontmatter } from '@/types'

export const MDX_DATA: Record<string, Frontmatter> = {
  GettingStarted: {
    title: 'Getting started',
    package: '@mantine-vue/core',
    slug: '/getting-started',
    description: 'Learn how to install Mantine Vue and start a project with official templates',
    docs: 'getting-started.mdx',
    searchTags: 'getting started, installation, vite, nuxt, templates, setup',
  },
  GuideVite: {
    title: 'Usage with Vite',
    package: '@mantine-vue/core',
    slug: '/guides/vite',
    description: 'Learn how to use Mantine Vue with Vue 3 and Vite',
    docs: 'guides/vite.mdx',
    searchTags: 'vite, vue, setup, guide',
  },
  GuideNuxt: {
    title: 'Usage with Nuxt',
    package: '@mantine-vue/core',
    slug: '/guides/nuxt',
    description: 'Learn how to use Mantine Vue with Nuxt and SSR',
    docs: 'guides/nuxt.mdx',
    searchTags: 'nuxt, ssr, vue, setup, guide',
  },
  GuideVueRouter: {
    title: 'Usage with Vue Router',
    package: '@mantine-vue/core',
    slug: '/guides/vue-router',
    description: 'Learn how to use Mantine Vue with Vue Router',
    docs: 'guides/vue-router.mdx',
    searchTags: 'vue router, spa, router, setup, guide',
  },
  GuideWithoutFramework: {
    title: 'Usage without a framework',
    package: '@mantine-vue/core',
    slug: '/guides/without-framework',
    description: 'Learn how to use Mantine Vue with a custom Vue setup',
    docs: 'guides/without-framework.mdx',
    searchTags: 'manual setup, no framework, postcss, provider',
  },
  AppShell: {
    title: 'AppShell',
    package: '@mantine-vue/core',
    slug: '/core/app-shell',
    description: 'Responsive shell for your application with header, navbar, aside and footer',
    componentPrefix: 'AppShell',
    props: ['AppShell', 'AppShellNavbar', 'AppShellHeader', 'AppShellAside', 'AppShellFooter'],
    styles: ['AppShell'],
    source: '@mantine-vue/core/src/components/AppShell/AppShell.ts',
    docs: 'core/app-shell.mdx',
    searchTags: 'app shell, application layout, navbar, header, aside, footer',
  },
  PillsInput: {
    title: 'PillsInput',
    package: '@mantine-vue/core',
    slug: '/core/pills-input',
    description: 'Utility component to build custom tag and multi-select inputs',
    componentPrefix: 'PillsInput',
    props: ['PillsInput', 'PillsInputField'],
    styles: ['PillsInput'],
    source: '@mantine-vue/core/src/components/PillsInput/PillsInput.ts',
    docs: 'core/pills-input.mdx',
    searchTags: 'pillsinput, pills, input, tags, multiselect, combobox',
  },
  Pill: {
    title: 'Pill',
    package: '@mantine-vue/core',
    slug: '/core/pill',
    description: 'Displays value as a pill, designed to be used inside inputs',
    componentPrefix: 'Pill',
    props: ['Pill', 'PillGroup'],
    styles: ['Pill', 'PillGroup'],
    source: '@mantine-vue/core/src/components/Pill/Pill.ts',
    docs: 'core/pill.mdx',
    searchTags: 'pill, tag, badge, chip, multiselect, input',
  },
  MultiSelect: {
    title: 'MultiSelect',
    package: '@mantine-vue/core',
    slug: '/core/multi-select',
    description: 'Select multiple values from dropdown',
    componentPrefix: 'MultiSelect',
    props: ['MultiSelect'],
    styles: ['MultiSelect'],
    source: '@mantine-vue/core/src/components/MultiSelect/MultiSelect.ts',
    docs: 'core/multi-select.mdx',
    searchTags: 'multiselect, select, multiple, combobox, pills, tags, input',
  },
  TreeSelect: {
    title: 'TreeSelect',
    package: '@mantine-vue/core',
    slug: '/core/tree-select',
    description: 'Select value from hierarchical tree data',
    componentPrefix: 'TreeSelect',
    props: ['TreeSelect'],
    styles: ['TreeSelect'],
    source: '@mantine-vue/core/src/components/TreeSelect/TreeSelect.ts',
    docs: 'core/tree-select.mdx',
    searchTags: 'treeselect, tree, select, hierarchical, dropdown, input',
  },
  Modal: {
    title: 'Modal',
    package: '@mantine-vue/core',
    slug: '/core/modal',
    description: 'Display content in a modal dialog above the main page content',
    componentPrefix: 'Modal',
    props: ['Modal'],
    styles: ['Modal'],
    source: '@mantine-vue/core/src/components/Modal/Modal.ts',
    docs: 'core/modal.mdx',
    searchTags: 'modal, dialog, popup, overlay',
  },
  Drawer: {
    title: 'Drawer',
    package: '@mantine-vue/core',
    slug: '/core/drawer',
    description: 'Display overlay area at any side of the screen',
    componentPrefix: 'Drawer',
    props: ['Drawer'],
    styles: ['Drawer'],
    source: '@mantine-vue/core/src/components/Drawer/Drawer.ts',
    docs: 'core/drawer.mdx',
    searchTags: 'drawer, sidebar, panel, overlay, modal, slide',
  },
  Affix: {
    title: 'Affix',
    package: '@mantine-vue/core',
    slug: '/core/affix',
    description: 'Renders children inside portal at fixed position',
    componentPrefix: 'Affix',
    props: ['Affix'],
    styles: ['Affix'],
    source: '@mantine-vue/core/src/components/Affix/Affix.ts',
    docs: 'core/affix.mdx',
    searchTags: 'affix, fixed, position, portal, sticky',
  },
  Dialog: {
    title: 'Dialog',
    package: '@mantine-vue/core',
    slug: '/core/dialog',
    description: 'Simplified modal without overlay and focus trap',
    componentPrefix: 'Dialog',
    props: ['Dialog'],
    styles: ['Dialog'],
    source: '@mantine-vue/core/src/components/Dialog/Dialog.ts',
    docs: 'core/dialog.mdx',
    searchTags: 'dialog, modal, popup, overlay, notification',
  },
  FloatingIndicator: {
    title: 'FloatingIndicator',
    package: '@mantine-vue/core',
    slug: '/core/floating-indicator',
    description: 'Animated indicator that highlights the active element in a group',
    componentPrefix: 'FloatingIndicator',
    props: ['FloatingIndicator'],
    styles: ['FloatingIndicator'],
    source: '@mantine-vue/core/src/components/FloatingIndicator/FloatingIndicator.ts',
    docs: 'core/floating-indicator.mdx',
    searchTags: 'floating indicator, tabs, segmented control, highlight, active',
  },
  FloatingWindow: {
    title: 'FloatingWindow',
    package: '@mantine-vue/core',
    slug: '/core/floating-window',
    description: 'Draggable floating window with fixed position',
    componentPrefix: 'FloatingWindow',
    props: ['FloatingWindow'],
    styles: ['FloatingWindow'],
    source: '@mantine-vue/core/src/components/FloatingWindow/FloatingWindow.ts',
    docs: 'core/floating-window.mdx',
    searchTags: 'floating window, draggable, fixed, overlay, panel',
  },
  HoverCard: {
    title: 'HoverCard',
    package: '@mantine-vue/core',
    slug: '/core/hover-card',
    description: 'Display popover section when target element is hovered',
    componentPrefix: 'HoverCard',
    props: ['HoverCard', 'HoverCardTarget', 'HoverCardDropdown', 'HoverCardGroup'],
    styles: ['HoverCard'],
    source: '@mantine-vue/core/src/components/HoverCard/HoverCard.ts',
    docs: 'core/hover-card.mdx',
    searchTags: 'hover card, popover, tooltip, hover, dropdown',
  },
  Popover: {
    title: 'Popover',
    package: '@mantine-vue/core',
    slug: '/core/popover',
    description: 'Displays floating content relative to a target element',
    componentPrefix: 'Popover',
    props: ['Popover', 'PopoverTarget', 'PopoverDropdown'],
    styles: ['Popover'],
    source: '@mantine-vue/core/src/components/Popover/Popover.ts',
    docs: 'core/popover.mdx',
    searchTags: 'popover, dropdown, floating, overlay, tooltip, menu',
  },
  Tooltip: {
    title: 'Tooltip',
    package: '@mantine-vue/core',
    slug: '/core/tooltip',
    description: 'Renders tooltip at a given element on mouse hover',
    componentPrefix: 'Tooltip',
    props: ['Tooltip', 'TooltipFloating', 'TooltipGroup'],
    styles: ['Tooltip'],
    source: '@mantine-vue/core/src/components/Tooltip/Tooltip.ts',
    docs: 'core/tooltip.mdx',
    searchTags: 'tooltip, hover, floating, label, popover',
  },
  Transition: {
    title: 'Transition',
    package: '@mantine-vue/core',
    slug: '/core/transition',
    description: 'Animate presence of a component with premade or custom transitions',
    componentPrefix: 'Transition',
    props: ['Transition'],
    styles: [],
    source: '@mantine-vue/core/src/components/Transition/Transition.ts',
    docs: 'core/transition.mdx',
    searchTags: 'transition, animation, fade, slide, scale, pop, motion, enter, exit, mounted',
  },
  Portal: {
    title: 'Portal',
    package: '@mantine-vue/core',
    slug: '/core/portal',
    description: 'Render component outside of parent element',
    componentPrefix: 'Portal',
    props: ['Portal', 'OptionalPortal'],
    styles: [],
    source: '@mantine-vue/core/src/components/Portal/Portal.ts',
    docs: 'core/portal.mdx',
    searchTags: 'portal, teleport, modal, overlay, z-index, fixed, body, render',
  },
  FocusTrap: {
    title: 'FocusTrap',
    package: '@mantine-vue/core',
    slug: '/core/focus-trap',
    description: 'Trap focus inside given node',
    componentPrefix: 'FocusTrap',
    props: ['FocusTrap'],
    styles: [],
    source: '@mantine-vue/core/src/components/FocusTrap/FocusTrap.ts',
    docs: 'core/focus-trap.mdx',
    searchTags: 'focus trap, focus, keyboard, accessibility, modal, dialog',
  },
  Overlay: {
    title: 'Overlay',
    package: '@mantine-vue/core',
    slug: '/core/overlay',
    description: 'Overlay element over any component',
    componentPrefix: 'Overlay',
    props: ['Overlay'],
    styles: ['Overlay'],
    polymorphic: true,
    source: '@mantine-vue/core/src/components/Overlay/Overlay.ts',
    docs: 'core/overlay.mdx',
    searchTags: 'overlay, backdrop, blur, gradient, opacity, modal, cover',
  },
  LoadingOverlay: {
    title: 'LoadingOverlay',
    package: '@mantine-vue/core',
    slug: '/core/loading-overlay',
    description: 'Overlay with loader over parent element with relative position',
    componentPrefix: 'LoadingOverlay',
    props: ['LoadingOverlay'],
    styles: ['LoadingOverlay'],
    source: '@mantine-vue/core/src/components/LoadingOverlay/LoadingOverlay.ts',
    docs: 'core/loading-overlay.mdx',
    searchTags: 'loading overlay, loader, spinner, overlay, loading state',
  },
  Menu: {
    title: 'Menu',
    package: '@mantine-vue/core',
    slug: '/core/menu',
    description: 'Combine a list of secondary actions into a single interactive area',
    componentPrefix: 'Menu',
    props: ['Menu', 'MenuItem', 'MenuLabel', 'MenuDropdown', 'MenuTarget', 'MenuDivider'],
    styles: ['Menu'],
    source: '@mantine-vue/core/src/components/Menu/Menu.ts',
    docs: 'core/menu.mdx',
    searchTags: 'menu, dropdown, context menu, navigation, actions',
  },
  SegmentedControl: {
    title: 'SegmentedControl',
    package: '@mantine-vue/core',
    slug: '/core/segmented-control',
    description: 'Inline radio group with improved styling',
    componentPrefix: 'SegmentedControl',
    props: ['SegmentedControl'],
    styles: ['SegmentedControl'],
    source: '@mantine-vue/core/src/components/SegmentedControl/SegmentedControl.ts',
    docs: 'core/segmented-control.mdx',
    searchTags: 'segmentedcontrol, segmented, control, radio, tabs, switch',
  },
  Switch: {
    title: 'Switch',
    package: '@mantine-vue/core',
    slug: '/core/switch',
    description: 'Capture boolean input from user',
    componentPrefix: 'Switch',
    props: ['Switch', 'SwitchGroup'],
    styles: ['Switch'],
    source: '@mantine-vue/core/src/components/Switch/Switch.ts',
    docs: 'core/switch.mdx',
    searchTags: 'switch, toggle, checkbox, boolean, input, group',
  },
  TagsInput: {
    title: 'TagsInput',
    package: '@mantine-vue/core',
    slug: '/core/tags-input',
    description: 'Free-form input with multiple values as tags',
    componentPrefix: 'TagsInput',
    props: ['TagsInput'],
    styles: ['TagsInput'],
    source: '@mantine-vue/core/src/components/TagsInput/TagsInput.ts',
    docs: 'core/tags-input.mdx',
    searchTags: 'tagsinput, tags, input, pills, multiselect, combobox',
  },
  Select: {
    title: 'Select',
    package: '@mantine-vue/core',
    slug: '/core/select',
    description: 'Custom select input',
    componentPrefix: 'Select',
    props: ['Select'],
    styles: ['Select'],
    source: '@mantine-vue/core/src/components/Select/Select.ts',
    docs: 'core/select.mdx',
    searchTags: 'select, combobox, dropdown, input, options',
  },
  Autocomplete: {
    title: 'Autocomplete',
    package: '@mantine-vue/core',
    slug: '/core/autocomplete',
    description: 'Text input with suggestions based on user input',
    componentPrefix: 'Autocomplete',
    props: ['Autocomplete'],
    styles: ['Autocomplete'],
    source: '@mantine-vue/core/src/components/Autocomplete/Autocomplete.ts',
    docs: 'core/autocomplete.mdx',
    searchTags: 'autocomplete, combobox, input, suggestions, search, typeahead',
  },
  Combobox: {
    title: 'Combobox',
    package: '@mantine-vue/core',
    slug: '/core/combobox',
    componentPrefix: 'Combobox',
    props: [
      'Combobox',
      'ComboboxOption',
      'ComboboxTarget',
      'ComboboxDropdownTarget',
      'ComboboxEventsTarget',
      'ComboboxDropdown',
      'ComboboxGroup',
    ],
    styles: ['Combobox'],
    description: 'Create custom select, autocomplete or multiselect inputs',
    source: '@mantine-vue/core/src/components/Combobox/Combobox.ts',
    docs: 'core/combobox.mdx',
    searchTags:
      'dropdown, autocomplete, typeahead, listbox, select custom, options, useCombobox, use-combobox',
  },
  AngleSlider: {
    title: 'AngleSlider',
    package: '@mantine-vue/core',
    slug: '/core/angle-slider',
    description: 'Pick an angle between 0 and 360 degrees',
    componentPrefix: 'AngleSlider',
    props: ['AngleSlider'],
    styles: ['AngleSlider'],
    source: '@mantine-vue/core/src/components/AngleSlider/AngleSlider.ts',
    docs: 'core/angle-slider.mdx',
    searchTags: 'angle slider, radial, rotate, degree, gradient, knob',
  },
  ActionIcon: {
    title: 'ActionIcon',
    package: '@mantine-vue/core',
    slug: '/core/action-icon',
    description: 'Icon button component',
    componentPrefix: 'ActionIcon',
    props: ['ActionIcon', 'ActionIconGroup', 'ActionIconGroupSection'],
    styles: ['ActionIcon', 'ActionIconGroup', 'ActionIconGroupSection'],
    source: '@mantine-vue/core/src/components/ActionIcon/ActionIcon.ts',
    docs: 'core/action-icon.mdx',
    searchTags: 'action icon, icon button, close, like, heart, star, button',
    polymorphic: true,
  },
  Button: {
    title: 'Button',
    package: '@mantine-vue/core',
    slug: '/core/button',
    description: 'Button component to render button or link',
    componentPrefix: 'Button',
    props: ['Button', 'ButtonGroup', 'ButtonGroupSection'],
    styles: ['Button', 'ButtonGroup', 'ButtonGroupSection'],
    source: '@mantine-vue/core/src/components/Button/Button.ts',
    docs: 'core/button.mdx',
    searchTags: 'action, cta, submit, button group, link button',
    polymorphic: true,
  },
  PinInput: {
    title: 'PinInput',
    package: '@mantine-vue/core',
    slug: '/core/pin-input',
    description: 'Capture PIN code or one time password',
    componentPrefix: 'PinInput',
    props: ['PinInput'],
    styles: ['PinInput'],
    source: '@mantine-vue/core/src/components/PinInput/PinInput.ts',
    docs: 'core/pin-input.mdx',
    searchTags: 'pin, otp, one-time, code, password, verification, input',
  },
  TextInput: {
    title: 'TextInput',
    package: '@mantine-vue/core',
    slug: '/core/text-input',
    description: 'Capture string input from user',
    componentPrefix: 'TextInput',
    props: ['TextInput'],
    styles: ['TextInput'],
    source: '@mantine-vue/core/src/components/TextInput/TextInput.ts',
    docs: 'core/text-input.mdx',
    searchTags: 'text, input, form, string, label, placeholder, sections',
  },
  Textarea: {
    title: 'Textarea',
    package: '@mantine-vue/core',
    slug: '/core/textarea',
    description: 'Multiline text input',
    componentPrefix: 'Textarea',
    props: ['Textarea'],
    styles: ['Textarea'],
    source: '@mantine-vue/core/src/components/Textarea/Textarea.ts',
    docs: 'core/textarea.mdx',
    searchTags: 'textarea, input, multiline, text, form, autosize, resize',
  },
  Slider: {
    title: 'Slider',
    package: '@mantine-vue/core',
    slug: '/core/slider',
    description: 'Slider to select value from a given range',
    componentPrefix: 'Slider',
    props: ['Slider'],
    styles: ['Slider'],
    source: '@mantine-vue/core/src/components/Slider/Slider/Slider.ts',
    docs: 'core/slider.mdx',
    searchTags: 'slider, range, input, form, step, marks, track, thumb',
  },
  Rating: {
    title: 'Rating',
    package: '@mantine-vue/core',
    slug: '/core/rating',
    description: 'Pick and display ratings',
    componentPrefix: 'Rating',
    props: ['Rating'],
    styles: ['Rating'],
    source: '@mantine-vue/core/src/components/Rating/Rating.ts',
    docs: 'core/rating.mdx',
    searchTags: 'rating, stars, review, score, feedback, symbol',
  },
  RangeSlider: {
    title: 'RangeSlider',
    package: '@mantine-vue/core',
    slug: '/core/range-slider',
    description: 'Slider with two thumbs to select a range of values',
    componentPrefix: 'RangeSlider',
    props: ['RangeSlider'],
    styles: ['RangeSlider'],
    source: '@mantine-vue/core/src/components/Slider/RangeSlider/RangeSlider.ts',
    docs: 'core/range-slider.mdx',
    searchTags: 'range, slider, input, form, min, max, values, between',
  },
  Radio: {
    title: 'Radio',
    package: '@mantine-vue/core',
    slug: '/core/radio',
    description: 'Capture boolean input from user',
    componentPrefix: 'Radio',
    props: ['Radio', 'RadioGroup', 'RadioIndicator', 'RadioCard'],
    styles: ['Radio', 'RadioGroup', 'RadioIndicator', 'RadioCard'],
    source: '@mantine-vue/core/src/components/Radio/Radio.ts',
    docs: 'core/radio.mdx',
    searchTags: 'radio, input, form, group, card, indicator, select, option',
  },
  PasswordInput: {
    title: 'PasswordInput',
    package: '@mantine-vue/core',
    slug: '/core/password-input',
    description: 'Input with password visibility toggle',
    componentPrefix: 'PasswordInput',
    props: ['PasswordInput'],
    styles: ['PasswordInput'],
    source: '@mantine-vue/core/src/components/PasswordInput/PasswordInput.ts',
    docs: 'core/password-input.mdx',
    searchTags: 'password, input, visibility, toggle, secure, secret',
  },
  NumberInput: {
    title: 'NumberInput',
    package: '@mantine-vue/core',
    slug: '/core/number-input',
    description: 'Number input with increment/decrement controls',
    componentPrefix: 'NumberInput',
    props: ['NumberInput'],
    styles: ['NumberInput'],
    source: '@mantine-vue/core/src/components/NumberInput/NumberInput.ts',
    docs: 'core/number-input.mdx',
    searchTags: 'number, input, increment, decrement, decimal, format, currency, bigint',
  },
  NativeSelect: {
    title: 'NativeSelect',
    package: '@mantine-vue/core',
    slug: '/core/native-select',
    description: 'Capture user feedback limited to large set of options',
    componentPrefix: 'NativeSelect',
    props: ['NativeSelect'],
    styles: ['NativeSelect'],
    source: '@mantine-vue/core/src/components/NativeSelect/NativeSelect.ts',
    docs: 'core/native-select.mdx',
    searchTags: 'select, native, dropdown, options, form, input',
  },
  MaskInput: {
    title: 'MaskInput',
    package: '@mantine-vue/core',
    slug: '/core/mask-input',
    description: 'Input with mask support',
    componentPrefix: 'MaskInput',
    props: ['MaskInput'],
    styles: ['MaskInput'],
    source: '@mantine-vue/core/src/components/MaskInput/MaskInput.ts',
    docs: 'core/mask-input.mdx',
    searchTags: 'mask, input, phone, credit card, format, pattern',
  },
  JsonInput: {
    title: 'JsonInput',
    package: '@mantine-vue/core',
    slug: '/core/json-input',
    description: 'Textarea with JSON validation and formatting',
    componentPrefix: 'JsonInput',
    props: ['JsonInput'],
    styles: ['JsonInput'],
    source: '@mantine-vue/core/src/components/JsonInput/JsonInput.ts',
    docs: 'core/json-input.mdx',
    searchTags: 'json, textarea, validate, format, code, input',
  },
  Input: {
    title: 'Input',
    package: '@mantine-vue/core',
    slug: '/core/input',
    description: 'Base component to create custom inputs',
    componentPrefix: 'Input',
    props: [
      'Input',
      'InputWrapper',
      'InputLabel',
      'InputDescription',
      'InputError',
      'InputPlaceholder',
      'InputClearButton',
    ],
    styles: ['Input', 'InputWrapper'],
    source: '@mantine-vue/core/src/components/Input/Input.ts',
    docs: 'core/input.mdx',
    searchTags: 'form, text, base, wrapper, label, description, error',
  },
  HueSlider: {
    title: 'HueSlider',
    package: '@mantine-vue/core',
    slug: '/core/hue-slider',
    description: 'Slider to select hue color value',
    componentPrefix: 'HueSlider',
    props: ['HueSlider'],
    styles: ['HueSlider'],
    source: '@mantine-vue/core/src/components/ColorPicker/ColorSlider/ColorSlider.ts',
    docs: 'core/hue-slider.mdx',
    searchTags: 'color, hue, slider, picker',
  },
  FileInput: {
    title: 'FileInput',
    package: '@mantine-vue/core',
    slug: '/core/file-input',
    description: 'Capture files from user',
    componentPrefix: 'FileInput',
    props: ['FileInput'],
    styles: ['FileInput'],
    source: '@mantine-vue/core/src/components/FileInput/FileInput.ts',
    docs: 'core/file-input.mdx',
    searchTags: 'upload, file, attachment, input, form',
  },
  Fieldset: {
    title: 'Fieldset',
    package: '@mantine-vue/core',
    slug: '/core/fieldset',
    description: 'Group related elements in a form',
    componentPrefix: 'Fieldset',
    props: ['Fieldset'],
    styles: ['Fieldset'],
    source: '@mantine-vue/core/src/components/Fieldset/Fieldset.ts',
    docs: 'core/fieldset.mdx',
    searchTags: 'form, group, legend, disabled, border',
  },
  ColorPicker: {
    title: 'ColorPicker',
    package: '@mantine-vue/core',
    slug: '/core/color-picker',
    description: 'Pick colors in hex, rgb, hsl and other formats',
    componentPrefix: 'ColorPicker',
    props: ['ColorPicker'],
    styles: ['ColorPicker'],
    source: '@mantine-vue/core/src/components/ColorPicker/ColorPicker.ts',
    docs: 'core/color-picker.mdx',
    searchTags: 'color, picker, hex, rgb, hsl, swatch, saturation, hue, alpha',
  },
  ColorInput: {
    title: 'ColorInput',
    package: '@mantine-vue/core',
    slug: '/core/color-input',
    description: 'Capture color from user',
    componentPrefix: 'ColorInput',
    props: ['ColorInput'],
    styles: ['ColorInput'],
    source: '@mantine-vue/core/src/components/ColorInput/ColorInput.ts',
    docs: 'core/color-input.mdx',
    searchTags: 'color, picker, hex, rgb, hsl, swatch, eye dropper',
  },
  Chip: {
    title: 'Chip',
    package: '@mantine-vue/core',
    slug: '/core/chip',
    description: 'Pick one or multiple values with inline controls',
    componentPrefix: 'Chip',
    props: ['Chip', 'ChipGroup'],
    styles: ['Chip', 'ChipGroup'],
    source: '@mantine-vue/core/src/components/Chip/Chip.ts',
    docs: 'core/chip.mdx',
    searchTags: 'tag, badge, filter, toggle, multi-select, radio, checkbox',
  },
  Checkbox: {
    title: 'Checkbox',
    package: '@mantine-vue/core',
    slug: '/core/checkbox',
    description: 'Capture boolean input from user',
    componentPrefix: 'Checkbox',
    props: ['Checkbox', 'CheckboxGroup', 'CheckboxIndicator', 'CheckboxCard'],
    styles: ['Checkbox', 'CheckboxGroup', 'CheckboxIndicator', 'CheckboxCard'],
    source: '@mantine-vue/core/src/components/Checkbox/Checkbox.ts',
    docs: 'core/checkbox.mdx',
    searchTags: 'input, boolean, toggle, form, indeterminate, group',
  },
  Space: {
    title: 'Space',
    package: '@mantine-vue/core',
    slug: '/core/space',
    description: 'Add horizontal or vertical spacing between elements',
    componentPrefix: 'Space',
    props: ['Space'],
    styles: ['Space'],
    source: '@mantine-vue/core/src/components/Space/Space.ts',
    docs: 'core/space.mdx',
    searchTags: 'gap, spacer, margin, padding, spacing',
  },
  Stack: {
    title: 'Stack',
    package: '@mantine-vue/core',
    slug: '/core/stack',
    description: 'Compose elements and components in a vertical flex container',
    componentPrefix: 'Stack',
    props: ['Stack'],
    styles: ['Stack'],
    source: '@mantine-vue/core/src/components/Stack/Stack.ts',
    docs: 'core/stack.mdx',
    searchTags: 'flex, vertical, column, layout, gap',
  },
  Flex: {
    title: 'Flex',
    package: '@mantine-vue/core',
    slug: '/core/flex',
    description: 'Compose elements in a flex container with full control over flexbox properties',
    componentPrefix: 'Flex',
    props: ['Flex'],
    styles: ['Flex'],
    source: '@mantine-vue/core/src/components/Flex/Flex.ts',
    docs: 'core/flex.mdx',
    searchTags: 'flexbox, layout, row, column, align, justify, wrap, gap, responsive',
    polymorphic: true,
  },
  Container: {
    title: 'Container',
    package: '@mantine-vue/core',
    slug: '/core/container',
    description: 'Center content horizontally with a max-width',
    componentPrefix: 'Container',
    props: ['Container'],
    styles: ['Container'],
    source: '@mantine-vue/core/src/components/Container/Container.ts',
    docs: 'core/container.mdx',
    searchTags: 'container, layout, center, max-width, fluid, responsive, grid, breakout',
  },
  Grid: {
    title: 'Grid',
    package: '@mantine-vue/core',
    slug: '/core/grid',
    description: 'Flexbox grid system with variable amount of columns',
    componentPrefix: 'Grid',
    props: ['Grid', 'GridCol'],
    styles: ['Grid', 'GridCol'],
    source: '@mantine-vue/core/src/components/Grid/Grid.ts',
    docs: 'core/grid.mdx',
    searchTags: 'grid, layout, columns, responsive, span, offset, container queries',
  },
  Group: {
    title: 'Group',
    package: '@mantine-vue/core',
    slug: '/core/group',
    description: 'Compose elements and components in a horizontal flex container',
    componentPrefix: 'Group',
    props: ['Group'],
    styles: ['Group'],
    source: '@mantine-vue/core/src/components/Group/Group.ts',
    docs: 'core/group.mdx',
    searchTags: 'flex, horizontal, row, layout, gap, grow, align',
  },
  SimpleGrid: {
    title: 'SimpleGrid',
    package: '@mantine-vue/core',
    slug: '/core/simple-grid',
    description: 'Responsive grid with equal-width columns',
    componentPrefix: 'SimpleGrid',
    props: ['SimpleGrid'],
    styles: ['SimpleGrid'],
    source: '@mantine-vue/core/src/components/SimpleGrid/SimpleGrid.ts',
    docs: 'core/simple-grid.mdx',
    searchTags:
      'grid, layout, columns, responsive, css grid, container queries, auto-fill, auto-fit',
  },
  CloseButton: {
    title: 'CloseButton',
    package: '@mantine-vue/core',
    slug: '/core/close-button',
    description: 'Button with a close icon, used in other Mantine components',
    componentPrefix: 'CloseButton',
    props: ['CloseButton'],
    styles: ['CloseButton'],
    source: '@mantine-vue/core/src/components/CloseButton/CloseButton.ts',
    docs: 'core/close-button.mdx',
    searchTags: 'close, dismiss, icon button, x button',
  },
  CopyButton: {
    title: 'CopyButton',
    package: '@mantine-vue/core',
    slug: '/core/copy-button',
    description: 'Copies given value to clipboard',
    componentPrefix: 'CopyButton',
    props: ['CopyButton'],
    styles: ['CopyButton'],
    source: '@mantine-vue/core/src/components/CopyButton/CopyButton.ts',
    docs: 'core/copy-button.mdx',
    searchTags: 'clipboard, copy, paste, scoped slot',
  },
  Burger: {
    title: 'Burger',
    package: '@mantine-vue/core',
    slug: '/core/burger',
    description: 'Open/close navigation button',
    componentPrefix: 'Burger',
    props: ['Burger'],
    styles: ['Burger'],
    source: '@mantine-vue/core/src/components/Burger/Burger.ts',
    docs: 'core/burger.mdx',
    searchTags: 'hamburger, menu, navigation, toggle, open, close',
  },
  Breadcrumbs: {
    title: 'Breadcrumbs',
    package: '@mantine-vue/core',
    slug: '/core/breadcrumbs',
    description: 'Display a series of links with a separator between them',
    componentPrefix: 'Breadcrumbs',
    props: ['Breadcrumbs'],
    styles: ['Breadcrumbs'],
    source: '@mantine-vue/core/src/components/Breadcrumbs/Breadcrumbs.ts',
    docs: 'core/breadcrumbs.mdx',
    searchTags: 'navigation, path, trail, separator, anchor, links',
  },
  NavLink: {
    title: 'NavLink',
    package: '@mantine-vue/core',
    slug: '/core/nav-link',
    description: 'Navigation link with optional icon, description, right section and nested links',
    componentPrefix: 'NavLink',
    props: ['NavLink'],
    styles: ['NavLink'],
    source: '@mantine-vue/core/src/components/NavLink/NavLink.ts',
    docs: 'core/nav-link.mdx',
    searchTags: 'navigation, sidebar, menu, link, nested, active, icon',
    polymorphic: true,
  },
  Anchor: {
    title: 'Anchor',
    package: '@mantine-vue/core',
    slug: '/core/anchor',
    description: 'Display link with theme styles',
    componentPrefix: 'Anchor',
    props: ['Anchor'],
    styles: ['Anchor'],
    source: '@mantine-vue/core/src/components/Anchor/Anchor.ts',
    docs: 'core/anchor.mdx',
    searchTags: 'link, href, url, text, navigation',
    polymorphic: true,
  },
  Avatar: {
    title: 'Avatar',
    package: '@mantine-vue/core',
    slug: '/core/avatar',
    description: 'Display user profile image, initials or fallback icon',
    componentPrefix: 'Avatar',
    props: ['Avatar', 'AvatarGroup'],
    styles: ['Avatar', 'AvatarGroup'],
    source: '@mantine-vue/core/src/components/Avatar/Avatar.ts',
    docs: 'core/avatar.mdx',
    searchTags: 'image, profile, user, initials, group, stack, placeholder',
    polymorphic: true,
  },
  NumberFormatter: {
    title: 'NumberFormatter',
    package: '@mantine-vue/core',
    slug: '/core/number-formatter',
    description: 'Formats numbers with prefix, suffix, thousands separator and decimal scale',
    componentPrefix: 'NumberFormatter',
    props: ['NumberFormatter'],
    styles: ['NumberFormatter'],
    source: '@mantine-vue/core/src/components/NumberFormatter/NumberFormatter.ts',
    docs: 'core/number-formatter.mdx',
    searchTags: 'number, format, currency, decimal, thousands, prefix, suffix',
  },
  ThemeIcon: {
    title: 'ThemeIcon',
    package: '@mantine-vue/core',
    slug: '/core/theme-icon',
    description: 'Render icon inside element with theme colors',
    componentPrefix: 'ThemeIcon',
    props: ['ThemeIcon'],
    styles: ['ThemeIcon'],
    source: '@mantine-vue/core/src/components/ThemeIcon/ThemeIcon.ts',
    docs: 'core/theme-icon.mdx',
    searchTags: 'icon, color, filled, light, outline, gradient, badge',
  },
  Blockquote: {
    title: 'Blockquote',
    package: '@mantine-vue/core',
    slug: '/core/blockquote',
    description: 'Display blockquote with optional cite',
    componentPrefix: 'Blockquote',
    props: ['Blockquote'],
    styles: ['Blockquote'],
    source: '@mantine-vue/core/src/components/Blockquote/Blockquote.ts',
    docs: 'core/blockquote.mdx',
    searchTags: 'quote, cite, pullquote, text',
  },
  Highlight: {
    title: 'Highlight',
    package: '@mantine-vue/core',
    slug: '/core/highlight',
    description: 'Highlight given part of a string with mark tag',
    componentPrefix: 'Highlight',
    props: ['Highlight'],
    styles: ['Highlight'],
    source: '@mantine-vue/core/src/components/Highlight/Highlight.ts',
    docs: 'core/highlight.mdx',
    searchTags: 'mark, text, search, match, substring, emphasize',
  },
  Mark: {
    title: 'Mark',
    package: '@mantine-vue/core',
    slug: '/core/mark',
    description: 'Highlight part of the text',
    componentPrefix: 'Mark',
    props: ['Mark'],
    styles: ['Mark'],
    source: '@mantine-vue/core/src/components/Mark/Mark.ts',
    docs: 'core/mark.mdx',
    searchTags: 'highlight, text, color, emphasis',
  },
  Kbd: {
    title: 'Kbd',
    package: '@mantine-vue/core',
    slug: '/core/kbd',
    description: 'Display keyboard shortcut',
    componentPrefix: 'Kbd',
    props: ['Kbd'],
    styles: ['Kbd'],
    source: '@mantine-vue/core/src/components/Kbd/Kbd.ts',
    docs: 'core/kbd.mdx',
    searchTags: 'keyboard, shortcut, hotkey, key, command',
  },
  Skeleton: {
    title: 'Skeleton',
    package: '@mantine-vue/core',
    slug: '/core/skeleton',
    description: 'Indicate content loading state',
    componentPrefix: 'Skeleton',
    props: ['Skeleton'],
    styles: ['Skeleton'],
    source: '@mantine-vue/core/src/components/Skeleton/Skeleton.ts',
    docs: 'core/skeleton.mdx',
    searchTags: 'loading, placeholder, shimmer, animation, content',
  },
  Alert: {
    title: 'Alert',
    package: '@mantine-vue/core',
    slug: '/core/alert',
    description: 'Attracts user attention with important static message',
    componentPrefix: 'Alert',
    props: ['Alert'],
    styles: ['Alert'],
    source: '@mantine-vue/core/src/components/Alert/Alert.ts',
    docs: 'core/alert.mdx',
    searchTags: 'notification, message, warning, error, info, success, banner',
  },
  Notification: {
    title: 'Notification',
    package: '@mantine-vue/core',
    slug: '/core/notification',
    props: ['Notification'],
    styles: ['Notification'],
    description: 'Show dynamic notifications and alerts to user, part of notifications system',
    source: '@mantine-vue/core/src/components/Notification/Notification.ts',
    docs: 'core/notification.mdx',
    searchTags: 'toast, snackbar, alert, message, popup message',
  },
  Loader: {
    title: 'Loader',
    package: '@mantine-vue/core',
    slug: '/core/loader',
    description: 'Indicate loading state',
    props: ['Loader'],
    styles: ['Loader'],
    source: '@mantine-vue/core/src/components/Loader/Loader.ts',
    docs: 'core/loader.mdx',
    searchTags: 'spinner, loading, progress, activity indicator, busy',
  },
  UnstyledButton: {
    title: 'UnstyledButton',
    package: '@mantine-vue/core',
    slug: '/core/unstyled-button',
    description: 'Unstyled polymorphic button',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/UnstyledButton/UnstyledButton.ts',
    docs: 'core/unstyled-button.mdx',
    searchTags: 'plain button, reset button, base button, clickable',
  },
  FileButton: {
    title: 'FileButton',
    package: '@mantine-vue/core',
    slug: '/core/file-button',
    description: 'Open file picker with a button click',
    props: ['FileButton'],
    source: '@mantine-vue/core/src/components/FileButton/FileButton.ts',
    docs: 'core/file-button.mdx',
    searchTags: 'upload, attach file, file picker, browse files, upload button',
  },
  AlphaSlider: {
    title: 'AlphaSlider',
    package: '@mantine-vue/core',
    slug: '/core/alpha-slider',
    props: ['AlphaSlider'],
    styles: ['AlphaSlider'],
    description: 'Slider component for selecting alpha channel in color pickers (0 – 1)',
    source: '@mantine-vue/core/src/components/ColorPicker/AlphaSlider/AlphaSlider.ts',
    docs: 'core/alpha-slider.mdx',
    searchTags: 'alpha, opacity slider, transparency, rgba alpha',
  },
  Center: {
    title: 'Center',
    package: '@mantine-vue/core',
    slug: '/core/center',
    props: ['Center'],
    styles: ['Center'],
    polymorphic: true,
    description: 'Centers content vertically and horizontally',
    source: '@mantine-vue/core/src/components/Center/Center.ts',
    docs: 'core/center.mdx',
    searchTags: 'align center, middle, centering, flex center',
  },
  AspectRatio: {
    title: 'AspectRatio',
    package: '@mantine-vue/core',
    slug: '/core/aspect-ratio',
    props: ['AspectRatio'],
    styles: ['AspectRatio'],
    description: 'Maintain responsive consistent width/height ratio',
    source: '@mantine-vue/core/src/components/AspectRatio/AspectRatio.ts',
    docs: 'core/aspect-ratio.mdx',
    searchTags: 'ratio, 16 9, responsive video, responsive iframe, proportions',
  },
  Badge: {
    title: 'Badge',
    package: '@mantine-vue/core',
    slug: '/core/badge',
    componentPrefix: 'Badge',
    props: ['Badge'],
    styles: ['Badge'],
    description: 'Display badge, pill or tag',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/Badge/Badge.ts',
    docs: 'core/badge.mdx',
    searchTags: 'pill, tag, label, chip, status, count',
  },
  BackgroundImage: {
    title: 'BackgroundImage',
    package: '@mantine-vue/core',
    slug: '/core/background-image',
    componentPrefix: 'BackgroundImage',
    props: ['BackgroundImage'],
    styles: ['BackgroundImage'],
    description: 'Displays image as background with child content',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/BackgroundImage/BackgroundImage.ts',
    docs: 'core/background-image.mdx',
    searchTags: 'background, image, hero, cover, banner',
  },
  SemiCircleProgress: {
    title: 'SemiCircleProgress',
    package: '@mantine-vue/core',
    slug: '/core/semi-circle-progress',
    componentPrefix: 'SemiCircleProgress',
    props: ['SemiCircleProgress'],
    styles: ['SemiCircleProgress'],
    description: 'Displays progress in a semi-circle form',
    source: '@mantine-vue/core/src/components/SemiCircleProgress/SemiCircleProgress.ts',
    docs: 'core/semi-circle-progress.mdx',
    searchTags: 'semi circle, gauge, progress, arc, half circle',
  },
  RingProgress: {
    title: 'RingProgress',
    package: '@mantine-vue/core',
    slug: '/core/ring-progress',
    componentPrefix: 'RingProgress',
    props: ['RingProgress'],
    styles: ['RingProgress'],
    description: 'Displays progress in a circular form',
    source: '@mantine-vue/core/src/components/RingProgress/RingProgress.ts',
    docs: 'core/ring-progress.mdx',
    searchTags: 'circular progress, donut, ring, radial, gauge',
  },
  Marquee: {
    title: 'Marquee',
    package: '@mantine-vue/core',
    slug: '/core/marquee',
    componentPrefix: 'Marquee',
    props: ['Marquee'],
    styles: ['Marquee'],
    description: 'Continuous scrolling animation for repeating content',
    source: '@mantine-vue/core/src/components/Marquee/Marquee.ts',
    docs: 'core/marquee.mdx',
    searchTags: 'ticker, scroll, carousel, infinite, loop, sliding, banner',
  },
  Table: {
    title: 'Table',
    package: '@mantine-vue/core',
    slug: '/core/table',
    componentPrefix: 'Table',
    props: ['Table'],
    styles: ['Table'],
    description: 'Render table with theme styles',
    source: '@mantine-vue/core/src/components/Table/Table.ts',
    docs: 'core/table.mdx',
    searchTags: 'grid, data table, rows, columns, spreadsheet',
  },
  Code: {
    title: 'Code',
    package: '@mantine-vue/core',
    slug: '/core/code',
    componentPrefix: 'Code',
    props: ['Code'],
    styles: ['Code'],
    description: 'Inline and block code',
    source: '@mantine-vue/core/src/components/Code/Code.ts',
    docs: 'core/code.mdx',
    searchTags: 'snippet, monospace, pre, inline code, code block',
  },
  List: {
    title: 'List',
    package: '@mantine-vue/core',
    slug: '/core/list',
    componentPrefix: 'List',
    props: ['List', 'ListItem'],
    styles: ['List'],
    description: 'Display ordered or unordered list',
    source: '@mantine-vue/core/src/components/List/List.ts',
    docs: 'core/list.mdx',
    searchTags: 'ul, ol, bullet list, numbered list, items list',
  },
  Text: {
    title: 'Text',
    package: '@mantine-vue/core',
    slug: '/core/text',
    componentPrefix: 'Text',
    props: ['Text'],
    styles: ['Text'],
    description: 'Display text',
    source: '@mantine-vue/core/src/components/Text/Text.ts',
    docs: 'core/text.mdx',
    searchTags: 'paragraph, typography, copy, p tag, span',
  },
  Title: {
    title: 'Title',
    package: '@mantine-vue/core',
    slug: '/core/title',
    componentPrefix: 'Title',
    props: ['Title'],
    styles: ['Title'],
    description: 'h1-h6 heading',
    source: '@mantine-vue/core/src/components/Title/Title.ts',
    docs: 'core/title.mdx',
    searchTags: 'heading, h1, h2, h3, h4, h5, h6, headline, header text',
  },
  Box: {
    title: 'Box',
    package: '@mantine-vue/core',
    slug: '/core/box',
    description: 'Base component for all Mantine Vue components',
    source: '@mantine-vue/core/src/core/Box/Box.ts',
    docs: 'core/box.mdx',
    searchTags: 'div, wrapper, base component, polymorphic box, style props',
  },
  VisuallyHidden: {
    title: 'VisuallyHidden',
    package: '@mantine-vue/core',
    slug: '/core/visually-hidden',
    componentPrefix: 'VisuallyHidden',
    props: ['VisuallyHidden'],
    styles: ['VisuallyHidden'],
    description: 'Hide element visually but keep it accessible for screen readers',
    source: '@mantine-vue/core/src/components/VisuallyHidden/VisuallyHidden.ts',
    docs: 'core/visually-hidden.mdx',
    searchTags: 'sr-only, screen reader, a11y, accessibility, hidden text',
  },
  Scroller: {
    title: 'Scroller',
    package: '@mantine-vue/core',
    slug: '/core/scroller',
    componentPrefix: 'Scroller',
    props: ['Scroller'],
    styles: ['Scroller'],
    description: 'Horizontal scroll container with navigation controls',
    source: '@mantine-vue/core/src/components/Scroller/Scroller.ts',
    docs: 'core/scroller.mdx',
    searchTags: 'horizontal scroll, carousel, snap scroll, arrows navigation, chip scroll',
  },
  ScrollArea: {
    title: 'ScrollArea',
    package: '@mantine-vue/core',
    slug: '/core/scroll-area',
    componentPrefix: 'ScrollArea',
    props: ['ScrollArea', 'ScrollAreaAutosize'],
    styles: ['ScrollArea'],
    description: 'Area with custom scrollbars',
    source: '@mantine-vue/core/src/components/ScrollArea/ScrollArea.ts',
    docs: 'core/scroll-area.mdx',
    searchTags: 'scrollbar, overflow, viewport, custom scrollbar, scroll container',
  },
  Collapse: {
    title: 'Collapse',
    package: '@mantine-vue/core',
    slug: '/core/collapse',
    componentPrefix: 'Collapse',
    props: ['Collapse'],
    styles: ['Collapse'],
    description: 'Animate presence of a component with slide animation',
    source: '@mantine-vue/core/src/components/Collapse/Collapse.ts',
    docs: 'core/collapse.mdx',
    searchTags: 'accordion, expand, toggle, show, hide, animation, transition',
  },
  Tree: {
    title: 'Tree',
    package: '@mantine-vue/core',
    slug: '/core/tree',
    componentPrefix: 'Tree',
    props: ['Tree'],
    styles: ['Tree'],
    description: 'Display hierarchical data',
    source: '@mantine-vue/core/src/components/Tree/Tree.ts',
    docs: 'core/tree.mdx',
    searchTags: 'tree, hierarchy, nodes, expand, collapse, file tree, nested',
  },
  Tabs: {
    title: 'Tabs',
    package: '@mantine-vue/core',
    slug: '/core/tabs',
    componentPrefix: 'Tabs',
    props: ['Tabs', 'TabsList', 'TabsTab', 'TabsPanel'],
    styles: ['Tabs'],
    description: 'Switch between different views',
    source: '@mantine-vue/core/src/components/Tabs/Tabs.ts',
    docs: 'core/tabs.mdx',
    searchTags: 'tab, panel, navigation, switch, tabbed, active tab',
  },
  TableOfContents: {
    title: 'TableOfContents',
    package: '@mantine-vue/core',
    slug: '/core/table-of-contents',
    componentPrefix: 'TableOfContents',
    props: ['TableOfContents'],
    styles: ['TableOfContents'],
    description: 'Display a table of contents with scroll spy',
    source: '@mantine-vue/core/src/components/TableOfContents/TableOfContents.ts',
    docs: 'core/table-of-contents.mdx',
    searchTags: 'toc, headings, scroll spy, anchor, navigation, sidebar',
  },
  Stepper: {
    title: 'Stepper',
    package: '@mantine-vue/core',
    slug: '/core/stepper',
    componentPrefix: 'Stepper',
    props: ['Stepper', 'StepperStep'],
    styles: ['Stepper'],
    description: 'Navigate between a series of steps',
    source: '@mantine-vue/core/src/components/Stepper/Stepper.ts',
    docs: 'core/stepper.mdx',
    searchTags: 'wizard, steps, progress, multi-step, form steps',
  },
  Pagination: {
    title: 'Pagination',
    package: '@mantine-vue/core',
    slug: '/core/pagination',
    componentPrefix: 'Pagination',
    props: ['Pagination', 'PaginationRoot'],
    styles: ['Pagination'],
    description: 'Display active page and navigate between multiple pages',
    source: '@mantine-vue/core/src/components/Pagination/Pagination.ts',
    docs: 'core/pagination.mdx',
    searchTags: 'pager, pages, navigation, page control, next, previous',
  },
  Paper: {
    title: 'Paper',
    package: '@mantine-vue/core',
    slug: '/core/paper',
    componentPrefix: 'Paper',
    props: ['Paper'],
    styles: ['Paper'],
    description: 'Renders element with white background and shadow',
    source: '@mantine-vue/core/src/components/Paper/Paper.ts',
    docs: 'core/paper.mdx',
    searchTags: 'card, container, surface, panel, shadow, elevation',
  },
  Progress: {
    title: 'Progress',
    package: '@mantine-vue/core',
    slug: '/core/progress',
    componentPrefix: 'Progress',
    props: ['Progress', 'ProgressRoot', 'ProgressSection', 'ProgressLabel'],
    styles: ['Progress'],
    description: 'Give user feedback for status of the task',
    source: '@mantine-vue/core/src/components/Progress/Progress.ts',
    docs: 'core/progress.mdx',
    searchTags: 'progress bar, loading bar, status, completion, indicator',
  },
  Splitter: {
    title: 'Splitter',
    package: '@mantine-vue/core',
    slug: '/core/splitter',
    componentPrefix: 'Splitter',
    props: ['Splitter', 'SplitterPane'],
    styles: ['Splitter'],
    description: 'Resizable split pane layout',
    source: '@mantine-vue/core/src/components/Splitter/Splitter.ts',
    docs: 'core/splitter.mdx',
    searchTags: 'split, resize, pane, panel, layout, collapsible',
  },
  Accordion: {
    title: 'Accordion',
    package: '@mantine-vue/core',
    slug: '/core/accordion',
    componentPrefix: 'Accordion',
    props: ['Accordion', 'AccordionItem', 'AccordionControl', 'AccordionPanel'],
    styles: ['Accordion'],
    description: 'Divide content into collapsible sections',
    source: '@mantine-vue/core/src/components/Accordion/Accordion.ts',
    docs: 'core/accordion.mdx',
    searchTags: 'collapse, expand, toggle, faq, panel, disclosure',
  },
  Card: {
    title: 'Card',
    package: '@mantine-vue/core',
    slug: '/core/card',
    componentPrefix: 'Card',
    props: ['Card', 'CardSection'],
    styles: ['Card', 'CardSection'],
    description: 'Card with sections',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/Card/Card.ts',
    docs: 'core/card.mdx',
    searchTags: 'card, paper, section, container, panel, tile',
  },
  OverflowList: {
    title: 'OverflowList',
    package: '@mantine-vue/core',
    slug: '/core/overflow-list',
    componentPrefix: 'OverflowList',
    props: ['OverflowList'],
    styles: ['OverflowList'],
    description: 'Renders a list of items, hiding overflowing items into a collapse indicator',
    source: '@mantine-vue/core/src/components/OverflowList/OverflowList.ts',
    docs: 'core/overflow-list.mdx',
    searchTags: 'overflow, collapse, truncate, more, badge list, tag list, responsive',
  },
  RollingNumber: {
    title: 'RollingNumber',
    package: '@mantine-vue/core',
    slug: '/core/rolling-number',
    componentPrefix: 'RollingNumber',
    props: ['RollingNumber'],
    styles: ['RollingNumber'],
    description: 'Animate number changes with rolling digit transitions',
    source: '@mantine-vue/core/src/components/RollingNumber/RollingNumber.ts',
    docs: 'core/rolling-number.mdx',
    searchTags: 'number, counter, animate, roll, digit, increment, odometer',
  },
  Spoiler: {
    title: 'Spoiler',
    package: '@mantine-vue/core',
    slug: '/core/spoiler',
    componentPrefix: 'Spoiler',
    props: ['Spoiler'],
    styles: ['Spoiler'],
    description: 'Hide long sections of content under a spoiler',
    source: '@mantine-vue/core/src/components/Spoiler/Spoiler.ts',
    docs: 'core/spoiler.mdx',
    searchTags: 'collapse, expand, truncate, read more, show more, hide',
  },
  ColorSwatch: {
    title: 'ColorSwatch',
    package: '@mantine-vue/core',
    slug: '/core/color-swatch',
    componentPrefix: 'ColorSwatch',
    props: ['ColorSwatch'],
    styles: ['ColorSwatch'],
    description: 'Display color swatch',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/ColorSwatch/ColorSwatch.ts',
    docs: 'core/color-swatch.mdx',
    searchTags: 'color, swatch, picker, palette, rgba, hex',
  },
  Image: {
    title: 'Image',
    package: '@mantine-vue/core',
    slug: '/core/image',
    componentPrefix: 'Image',
    props: ['Image'],
    styles: ['Image'],
    description: 'Image with optional fallback',
    polymorphic: true,
    source: '@mantine-vue/core/src/components/Image/Image.ts',
    docs: 'core/image.mdx',
    searchTags: 'img, photo, picture, fallback, responsive',
  },
  Indicator: {
    title: 'Indicator',
    package: '@mantine-vue/core',
    slug: '/core/indicator',
    componentPrefix: 'Indicator',
    props: ['Indicator'],
    styles: ['Indicator'],
    description: 'Display element at the corner of another element',
    source: '@mantine-vue/core/src/components/Indicator/Indicator.ts',
    docs: 'core/indicator.mdx',
    searchTags: 'badge, dot, notification, corner, overlay, counter',
  },
  Divider: {
    title: 'Divider',
    package: '@mantine-vue/core',
    slug: '/core/divider',
    componentPrefix: 'Divider',
    props: ['Divider'],
    styles: ['Divider'],
    description: 'Horizontal line with optional label or vertical divider',
    source: '@mantine-vue/core/src/components/Divider/Divider.ts',
    docs: 'core/divider.mdx',
    searchTags: 'separator, hr, line, horizontal rule, vertical, label, section',
  },
  Timeline: {
    title: 'Timeline',
    package: '@mantine-vue/core',
    slug: '/core/timeline',
    componentPrefix: 'Timeline',
    props: ['Timeline', 'TimelineItem'],
    styles: ['Timeline', 'TimelineItem'],
    description: 'Display list of events in chronological order',
    source: '@mantine-vue/core/src/components/Timeline/Timeline.ts',
    docs: 'core/timeline.mdx',
    searchTags: 'timeline, events, history, steps, chronological, activity',
  },
  Nprogress: {
    title: 'NavigationProgress',
    package: '@mantine-vue/nprogress',
    slug: '/x/nprogress',
    componentPrefix: 'NavigationProgress',
    props: ['NavigationProgress'],
    description: 'Navigation progress bar',
    source: '@mantine-vue/nprogress/src/NavigationProgress.ts',
    docs: 'x/nprogress.mdx',
    searchTags: 'top progress bar, page loading bar, route progress, nprogress, youtube bar',
  },
  Notifications: {
    title: 'Notifications system',
    package: '@mantine-vue/notifications',
    slug: '/x/notifications',
    componentPrefix: 'Notifications',
    props: ['Notifications'],
    styles: ['Notifications'],
    description: 'Mantine notifications system',
    source: '@mantine-vue/notifications/src/Notifications.ts',
    docs: 'x/notifications.mdx',
    searchTags: 'toast, snackbar, alerts, messages, notify, popup notification',
  },
  Spotlight: {
    title: 'Spotlight',
    package: '@mantine-vue/spotlight',
    slug: '/x/spotlight',
    componentPrefix: 'Spotlight',
    props: [
      'Spotlight',
      'SpotlightRoot',
      'SpotlightAction',
      'SpotlightActionsGroup',
      'SpotlightSearch',
    ],
    styles: ['Spotlight'],
    description: 'Command center for your application',
    source: '@mantine-vue/spotlight/src/Spotlight.ts',
    docs: 'x/spotlight.mdx',
    searchTags: 'search, command center, command palette, cmd k, ctrl k, quick actions',
  },
  Modals: {
    title: 'Modals manager',
    package: '@mantine-vue/modals',
    slug: '/x/modals',
    componentPrefix: 'Modals',
    props: ['ModalsProvider'],
    description: 'Open modals and confirmation dialogs imperatively',
    source: '@mantine-vue/modals/src/ModalsProvider.ts',
    docs: 'x/modals.mdx',
    searchTags: 'modal, dialog, confirm, popup, imperative, modals manager, context modal',
  },
  Dropzone: {
    title: 'Dropzone',
    package: '@mantine-vue/dropzone',
    slug: '/x/dropzone',
    componentPrefix: 'Dropzone',
    props: ['Dropzone', 'DropzoneFullScreen'],
    styles: ['Dropzone', 'DropzoneFullScreen'],
    description: 'Capture files from the user with drag and drop',
    source: '@mantine-vue/dropzone/src/Dropzone.ts',
    docs: 'x/dropzone.mdx',
    searchTags: 'dropzone, file upload, drag and drop, drop files, file picker, attachments',
  },
  Carousel: {
    title: 'Carousel',
    package: '@mantine-vue/carousel',
    slug: '/x/carousel',
    componentPrefix: 'Carousel',
    props: ['Carousel', 'CarouselSlide'],
    styles: ['Carousel'],
    description: 'Embla based carousel component',
    source: '@mantine-vue/carousel/src/Carousel.ts',
    docs: 'x/carousel.mdx',
    searchTags: 'carousel, slider, slideshow, embla, gallery, images carousel',
  },
  TipTap: {
    title: 'Rich text editor',
    package: '@mantine-vue/tiptap',
    slug: '/x/tiptap',
    componentPrefix: 'RichTextEditor',
    props: [
      'RichTextEditor',
      'RichTextEditorContent',
      'RichTextEditorControl',
      'RichTextEditorControlsGroup',
      'RichTextEditorToolbar',
    ],
    styles: ['RichTextEditor'],
    description: 'Rich text editor based on Tiptap',
    source: '@mantine-vue/tiptap/src/RichTextEditor.ts',
    docs: 'x/tiptap.mdx',
    searchTags: 'rich text editor, wysiwyg, tiptap, editor, markdown, content editor',
  },
  CodeHighlight: {
    title: 'CodeHighlight',
    package: '@mantine-vue/code-highlight',
    slug: '/x/code-highlight',
    componentPrefix: 'CodeHighlight',
    props: ['CodeHighlight', 'CodeHighlightTabs', 'InlineCodeHighlight', 'CodeHighlightControl'],
    styles: ['CodeHighlight', 'CodeHighlightTabs', 'InlineCodeHighlight'],
    description: 'Display code snippets with syntax highlighting',
    source: '@mantine-vue/code-highlight/src/CodeHighlight/CodeHighlight.ts',
    docs: 'x/code-highlight.mdx',
    searchTags: 'code highlight, syntax highlighting, shiki, highlight.js, code block, prism',
  },
  GettingStartedDates: {
    title: 'Getting started with dates',
    package: '@mantine-vue/dates',
    slug: '/dates/getting-started',
    description: 'Learn how to install and use @mantine-vue/dates package',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/getting-started.mdx',
    searchTags: 'dates, dayjs, calendar, date picker, getting started',
  },
  Calendar: {
    title: 'Calendar',
    package: '@mantine-vue/dates',
    slug: '/dates/calendar',
    componentPrefix: 'Calendar',
    props: ['Calendar'],
    styles: ['Calendar'],
    description: 'Displays date, month and year pickers',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/calendar.mdx',
    searchTags: 'calendar, date, month, year, picker',
  },
  DateInput: {
    title: 'DateInput',
    package: '@mantine-vue/dates',
    slug: '/dates/date-input',
    componentPrefix: 'DateInput',
    props: ['DateInput'],
    styles: ['DateInput'],
    description: 'Free input for date parsing and user modified text input',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/date-input.mdx',
    searchTags: 'date input, date parser, text input',
  },
  DatePicker: {
    title: 'DatePicker',
    package: '@mantine-vue/dates',
    slug: '/dates/date-picker',
    componentPrefix: 'DatePicker',
    props: ['DatePicker'],
    styles: ['DatePicker'],
    description: 'Displays date, month and year pickers with selection logic built in',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/date-picker.mdx',
    searchTags: 'date picker, calendar, range, multiple dates',
  },
  DatePickerInput: {
    title: 'DatePickerInput',
    package: '@mantine-vue/dates',
    slug: '/dates/date-picker-input',
    componentPrefix: 'DatePickerInput',
    props: ['DatePickerInput'],
    styles: ['DatePickerInput'],
    description: 'Input with date picker dropdown/modal',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/date-picker-input.mdx',
    searchTags: 'date picker input, calendar input, range, multiple dates',
  },
  DateTimePicker: {
    title: 'DateTimePicker',
    package: '@mantine-vue/dates',
    slug: '/dates/date-time-picker',
    componentPrefix: 'DateTimePicker',
    props: ['DateTimePicker'],
    styles: ['DateTimePicker'],
    description: 'Captures date and time input from user',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/date-time-picker.mdx',
    searchTags: 'date time picker, calendar, time picker',
  },
  InlineDateTimePicker: {
    title: 'InlineDateTimePicker',
    package: '@mantine-vue/dates',
    slug: '/dates/inline-date-time-picker',
    componentPrefix: 'DateTimePicker',
    props: ['DateTimePicker'],
    styles: ['DateTimePicker'],
    description: 'Displays date and time pickers inline',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/inline-date-time-picker.mdx',
    searchTags: 'inline date time picker, calendar, time picker',
  },
  MiniCalendar: {
    title: 'MiniCalendar',
    package: '@mantine-vue/dates',
    slug: '/dates/mini-calendar',
    componentPrefix: 'MiniCalendar',
    props: ['MiniCalendar'],
    styles: ['MiniCalendar'],
    description: 'Displays a horizontal strip of dates for quick selection',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/mini-calendar.mdx',
    searchTags: 'mini calendar, date strip, week picker',
  },
  MonthPicker: {
    title: 'MonthPicker',
    package: '@mantine-vue/dates',
    slug: '/dates/month-picker',
    componentPrefix: 'MonthPicker',
    props: ['MonthPicker'],
    styles: ['MonthPicker'],
    description: 'Displays year and month pickers with selection logic built in',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/month-picker.mdx',
    searchTags: 'month picker, calendar, range, multiple months',
  },
  MonthPickerInput: {
    title: 'MonthPickerInput',
    package: '@mantine-vue/dates',
    slug: '/dates/month-picker-input',
    componentPrefix: 'MonthPickerInput',
    props: ['MonthPickerInput'],
    styles: ['MonthPickerInput'],
    description: 'Input with month picker dropdown/modal',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/month-picker-input.mdx',
    searchTags: 'month picker input, calendar input',
  },
  YearPicker: {
    title: 'YearPicker',
    package: '@mantine-vue/dates',
    slug: '/dates/year-picker',
    componentPrefix: 'YearPicker',
    props: ['YearPicker'],
    styles: ['YearPicker'],
    description: 'Displays year picker with selection logic built in',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/year-picker.mdx',
    searchTags: 'year picker, calendar, range, multiple years',
  },
  YearPickerInput: {
    title: 'YearPickerInput',
    package: '@mantine-vue/dates',
    slug: '/dates/year-picker-input',
    componentPrefix: 'YearPickerInput',
    props: ['YearPickerInput'],
    styles: ['YearPickerInput'],
    description: 'Input with year picker dropdown/modal',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/year-picker-input.mdx',
    searchTags: 'year picker input, calendar input',
  },
  TimeInput: {
    title: 'TimeInput',
    package: '@mantine-vue/dates',
    slug: '/dates/time-input',
    componentPrefix: 'TimeInput',
    props: ['TimeInput'],
    styles: ['TimeInput'],
    description: 'Captures time input from user with native time input',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/time-input.mdx',
    searchTags: 'time input, native time input',
  },
  TimePicker: {
    title: 'TimePicker',
    package: '@mantine-vue/dates',
    slug: '/dates/time-picker',
    componentPrefix: 'TimePicker',
    props: ['TimePicker'],
    styles: ['TimePicker'],
    description: 'Custom time picker input implemented without native time input',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/time-picker.mdx',
    searchTags: 'time picker, hours, minutes, seconds',
  },
  TimeGrid: {
    title: 'TimeGrid',
    package: '@mantine-vue/dates',
    slug: '/dates/time-grid',
    componentPrefix: 'TimeGrid',
    props: ['TimeGrid'],
    styles: ['TimeGrid'],
    description: 'Displays a list of time values in a grid for quick selection',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/time-grid.mdx',
    searchTags: 'time grid, time slots, time selection',
  },
  TimeValue: {
    title: 'TimeValue',
    package: '@mantine-vue/dates',
    slug: '/dates/time-value',
    componentPrefix: 'TimeValue',
    props: ['TimeValue'],
    styles: ['TimeValue'],
    description: 'Formats and displays time value',
    source: '@mantine-vue/dates/src/index.ts',
    docs: 'dates/time-value.mdx',
    searchTags: 'time value, time format, display time',
  },
}
