/* oxlint-disable no-console */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

export interface WorkspaceManifest {
  path: string
  directory: string
  content: Record<string, any>
}

export const root = resolve(import.meta.dirname, '../..')

export function getWorkspaceManifests(): WorkspaceManifest[] {
  const manifests: WorkspaceManifest[] = []

  for (const workspaceRoot of ['packages', 'apps']) {
    const directory = join(root, workspaceRoot)
    const candidates = readdirSync(directory, { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name === 'package.json')
      .map((entry) => join(entry.parentPath, entry.name))

    for (const path of candidates) {
      // Ignore package manifests generated by nested dependency folders.
      if (path.includes(`${join('node_modules', '')}`)) {
        continue
      }

      manifests.push({
        path,
        directory: resolve(path, '..'),
        content: JSON.parse(readFileSync(path, 'utf8')),
      })
    }
  }

  return manifests.sort((a, b) => a.path.localeCompare(b.path))
}

export function failIfErrors(errors: string[], successMessage: string) {
  if (errors.length > 0) {
    errors.forEach((error) => console.error(`- ${error}`))
    process.exitCode = 1
    return
  }

  console.log(successMessage)
}

export { existsSync, readFileSync }
