import docgenData from '@/.docgen/docgen.json'

export interface DocgenProp {
  name: string
  type: { name: string }
  required: boolean
  description: string
  defaultValue: string | null
  /**
   * Repository-relative path of the file that declares the prop.
   */
  declaredIn?: string
}

export interface DocgenSlot {
  name: string
  type: { name: string }
  required: boolean
  description: string
  /**
   * Repository-relative path of the file that declares the slot.
   */
  declaredIn?: string
}

export interface Docgen {
  displayName: string
  description: string
  props: Record<string, DocgenProp>
  /** Omitted when the component does not declare a `*Slots` interface. */
  slots?: Record<string, DocgenSlot>
  /** Repository-relative path of the file that declares the props interface. */
  declaredIn?: string
}

/**
 * Generated by `yarn docgen` (see `scripts/docgen`).
 */
export const PROPS_DATA: Record<string, Docgen> = docgenData as unknown as Record<string, Docgen>

const REPLACE_TYPES: Record<string, string> = {}

export function prepareType(type: string): string {
  if (type in REPLACE_TYPES) {
    return REPLACE_TYPES[type]
  }

  return type.replaceAll('DefaultMantineColor', 'MantineColor').replaceAll('| undefined', '').trim()
}
