export { Tabs } from './Tabs'
export type { TabsStylesNames, TabsVariant } from './Tabs'
export { TabsList } from './TabsList/TabsList'
export type { TabsListStylesNames } from './TabsList/TabsList'
export { TabsTab } from './TabsTab/TabsTab'
export type { TabsTabStylesNames } from './TabsTab/TabsTab'
export { TabsPanel } from './TabsPanel/TabsPanel'
export type { TabsPanelStylesNames } from './TabsPanel/TabsPanel'
export { useTabsContext } from './Tabs.context'
export type { TabsContextValue } from './Tabs.context'
