/**
 * Mantine component prop-type bridge.
 *
 */
import {
  type ActionIconProps,
  type AlertProps,
  type AutocompleteProps,
  type BadgeProps,
  type BoxProps,
  type CheckboxProps,
  type HighlightProps,
  type LoadingOverlayProps,
  type ModalProps,
  type MultiSelectProps,
  type PaginationProps,
  type PaperProps,
  type ProgressProps,
  type RadioProps,
  type RangeSliderProps,
  type SelectProps,
  type SkeletonProps,
  type SwitchProps,
  type TableProps,
  type TableTbodyProps,
  type TableTdProps,
  type TableTfootProps,
  type TableThProps,
  type TableTheadProps,
  type TableTrProps,
  type TextInputProps,
  type UnstyledButtonProps,
} from '@mantine-vue/core'

export type {
  ActionIconProps,
  AlertProps,
  AutocompleteProps,
  BadgeProps,
  BoxProps,
  CheckboxProps,
  HighlightProps,
  LoadingOverlayProps,
  ModalProps,
  MultiSelectProps,
  PaginationProps,
  PaperProps,
  ProgressProps,
  RadioProps,
  RangeSliderProps,
  SelectProps,
  SkeletonProps,
  SwitchProps,
  TableProps,
  TableTbodyProps,
  TableTdProps,
  TableTfootProps,
  TableThProps,
  TableTheadProps,
  TableTrProps,
  TextInputProps,
  UnstyledButtonProps,
}

/** From `@mantine-vue/dates` not yet exported as a named interface. */
export type DateInputProps = BoxProps & Record<string, any>
