import type { BoxMod, BoxProps, StylesApiProps } from '../../../core'

export type PillsInputFieldStylesNames = 'field'

/**
 * Props declared by `PillsInputField` itself.
 * See `PillsInputFieldProps` for the full public type.
 */
export interface PillsInputFieldOwnProps extends StylesApiProps<PillsInputFieldProps> {
  /** Controlled value, bound with `v-model`. */
  modelValue?: string

  /** Uncontrolled initial value. */
  defaultValue?: string

  /**
   * Controls how the field is displayed: always visible, hidden, or sized to its
   * content.
   *
   * @default 'visible'
   */
  type?: 'auto' | 'visible' | 'hidden'

  /**
   * Sets `cursor: pointer` on the field, used when the input is read-only.
   *
   * @default false
   */
  pointer?: boolean

  /**
   * Sets the `disabled` attribute. The parent `PillsInput` `disabled` prop is applied
   * on top of this one.
   *
   * @default false
   */
  disabled?: boolean

  /** `id` of the field. Falls back to the id generated by the enclosing `Input.Wrapper`. */
  id?: string

  /** Ref assigned to the underlying `input` element. */
  inputRef?: any

  /** Element modifiers transformed into `data-` attributes, for example, `{ 'data-size': 'xl' }`, falsy values are removed */
  mod?: BoxMod
}

export interface PillsInputFieldProps
  extends Omit<BoxProps, keyof PillsInputFieldOwnProps>, PillsInputFieldOwnProps {}
