import type { VNodeChild } from 'vue'
import type { BoxMod, BoxProps, MantineRadius, StylesApiProps } from '../../../core'

export type RadioCardStylesNames = 'card'

export type RadioCardCssVariables = {
  card: '--card-radius'
}

export interface RadioCardContextValue {
  /** Checked state of the enclosing card, read by `Radio.Indicator`. */
  checked: boolean
}

export interface RadioCardSlots {
  /** Card content, usually a `Radio.Indicator` and a label. */
  default?: () => VNodeChild
}

/** Props declared by `RadioCard` itself. See `RadioCardProps` for the full public type. */
export interface RadioCardOwnProps extends StylesApiProps<RadioCardProps> {
  /** Checked state, bound with `v-model`. */
  modelValue?: boolean

  /** Checked state, bound with `v-model:checked`. */
  checked?: boolean

  /** Uncontrolled initial checked state. */
  defaultChecked?: boolean

  /**
   * If set, the card has a border.
   *
   * @default true
   */
  withBorder?: boolean

  /**
   * Key of `theme.radius` or any valid CSS value to set `border-radius`.
   *
   * @default theme.defaultRadius
   */
  radius?: MantineRadius

  /** Value used to associate the card with the enclosing `Radio.Group`. */
  value?: string

  /** `name` of the card. Falls back to the name generated by the enclosing `Radio.Group`. */
  name?: string

  /** Element modifiers transformed into `data-` attributes, for example, `{ 'data-size': 'xl' }`, falsy values are removed */
  mod?: BoxMod
}

export interface RadioCardProps
  extends Omit<BoxProps, keyof RadioCardOwnProps>, RadioCardOwnProps {}
