/**
 * Emoji dataset for the built-in picker.
 *
 * This curated subset limits bundle size. Entries are stored as tuples and expanded at module
 * load.
 *
 * Use the `emojiPicker` slot for a complete catalogue, skin-tone variants, or localized names.
 */

/** Category an emoji belongs to. Mirrors the tabs WhatsApp shows. */
export type WhatsAppEmojiGroupId =
  | 'recent'
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'activity'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags'

/** One entry of the dataset. */
export interface WhatsAppEmoji {
  /** Character inserted into the composer. */
  emoji: string

  /** Short name, used as the accessible name, the tooltip and the primary search term. */
  name: string

  /** Extra words the search matches on. */
  keywords: string[]

  /** Category the emoji is listed under. */
  group: WhatsAppEmojiGroupId
}

/** `[emoji, name, space separated keywords]`. */
type EmojiTuple = readonly [string, string, string?]

const SMILEYS: EmojiTuple[] = [
  ['😀', 'grinning face', 'smile happy joy'],
  ['😃', 'grinning face with big eyes', 'smile happy joy excited'],
  ['😄', 'grinning face with smiling eyes', 'smile happy laugh'],
  ['😁', 'beaming face with smiling eyes', 'grin smile'],
  ['😆', 'grinning squinting face', 'laugh haha satisfied'],
  ['😅', 'grinning face with sweat', 'laugh relief phew'],
  ['🤣', 'rolling on the floor laughing', 'rofl lol laugh'],
  ['😂', 'face with tears of joy', 'lol laugh cry funny'],
  ['🙂', 'slightly smiling face', 'smile'],
  ['🙃', 'upside down face', 'silly sarcasm'],
  ['😉', 'winking face', 'wink flirt'],
  ['😊', 'smiling face with smiling eyes', 'blush happy warm'],
  ['😇', 'smiling face with halo', 'angel innocent'],
  ['🥰', 'smiling face with hearts', 'love adore crush'],
  ['😍', 'smiling face with heart eyes', 'love crush'],
  ['🤩', 'star struck', 'starry eyes amazed excited'],
  ['😘', 'face blowing a kiss', 'kiss love'],
  ['😗', 'kissing face', 'kiss'],
  ['😚', 'kissing face with closed eyes', 'kiss'],
  ['😙', 'kissing face with smiling eyes', 'kiss'],
  ['😋', 'face savoring food', 'yum tasty delicious'],
  ['😛', 'face with tongue', 'tongue silly'],
  ['😜', 'winking face with tongue', 'tongue joke silly'],
  ['🤪', 'zany face', 'crazy goofy wild'],
  ['😝', 'squinting face with tongue', 'tongue prank'],
  ['🤑', 'money mouth face', 'rich dollar greedy'],
  ['🤗', 'hugging face', 'hug thanks'],
  ['🤭', 'face with hand over mouth', 'oops giggle whoops'],
  ['🤫', 'shushing face', 'quiet silence secret'],
  ['🤔', 'thinking face', 'hmm think consider'],
  ['🤐', 'zipper mouth face', 'quiet secret'],
  ['🤨', 'face with raised eyebrow', 'skeptic suspicious doubt'],
  ['😐', 'neutral face', 'meh blank'],
  ['😑', 'expressionless face', 'blank done'],
  ['😶', 'face without mouth', 'silent speechless'],
  ['😏', 'smirking face', 'smug flirt'],
  ['😒', 'unamused face', 'meh annoyed'],
  ['🙄', 'face with rolling eyes', 'eyeroll whatever'],
  ['😬', 'grimacing face', 'awkward eek'],
  ['🤥', 'lying face', 'liar pinocchio'],
  ['😌', 'relieved face', 'calm content'],
  ['😔', 'pensive face', 'sad dejected'],
  ['😪', 'sleepy face', 'tired'],
  ['🤤', 'drooling face', 'hungry want'],
  ['😴', 'sleeping face', 'sleep zzz tired'],
  ['😷', 'face with medical mask', 'sick mask ill'],
  ['🤒', 'face with thermometer', 'sick fever ill'],
  ['🤕', 'face with head bandage', 'hurt injured'],
  ['🤢', 'nauseated face', 'sick gross'],
  ['🤮', 'face vomiting', 'sick puke'],
  ['🤧', 'sneezing face', 'sick cold'],
  ['🥵', 'hot face', 'heat sweating'],
  ['🥶', 'cold face', 'freezing ice'],
  ['🥴', 'woozy face', 'dizzy tipsy'],
  ['😵', 'dizzy face', 'knocked out'],
  ['🤯', 'exploding head', 'mind blown shocked'],
  ['🤠', 'cowboy hat face', 'cowboy'],
  ['🥳', 'partying face', 'party celebrate birthday'],
  ['😎', 'smiling face with sunglasses', 'cool sunglasses'],
  ['🤓', 'nerd face', 'geek glasses'],
  ['🧐', 'face with monocle', 'inspect posh'],
  ['😕', 'confused face', 'unsure'],
  ['😟', 'worried face', 'concern'],
  ['🙁', 'slightly frowning face', 'sad'],
  ['😮', 'face with open mouth', 'surprise wow'],
  ['😯', 'hushed face', 'surprise'],
  ['😲', 'astonished face', 'shocked gasp'],
  ['😳', 'flushed face', 'embarrassed blush'],
  ['🥺', 'pleading face', 'begging puppy eyes'],
  ['😦', 'frowning face with open mouth', 'sad'],
  ['😨', 'fearful face', 'scared'],
  ['😰', 'anxious face with sweat', 'nervous'],
  ['😥', 'sad but relieved face', 'phew'],
  ['😢', 'crying face', 'sad tear'],
  ['😭', 'loudly crying face', 'sob cry sad'],
  ['😱', 'face screaming in fear', 'scream shocked'],
  ['😖', 'confounded face', 'frustrated'],
  ['😣', 'persevering face', 'struggling'],
  ['😞', 'disappointed face', 'sad'],
  ['😓', 'downcast face with sweat', 'tired sad'],
  ['😩', 'weary face', 'tired frustrated'],
  ['😫', 'tired face', 'exhausted'],
  ['🥱', 'yawning face', 'tired bored'],
  ['😤', 'face with steam from nose', 'triumph determined'],
  ['😡', 'enraged face', 'angry mad furious'],
  ['😠', 'angry face', 'mad'],
  ['🤬', 'face with symbols on mouth', 'swearing cursing'],
  ['😈', 'smiling face with horns', 'devil mischief'],
  ['💀', 'skull', 'dead'],
  ['💩', 'pile of poo', 'poop'],
  ['🤡', 'clown face', 'clown'],
  ['👻', 'ghost', 'halloween boo'],
  ['👽', 'alien', 'ufo space'],
  ['🤖', 'robot', 'bot machine'],
  ['😺', 'grinning cat', 'cat happy'],
  ['😸', 'grinning cat with smiling eyes', 'cat'],
  ['😹', 'cat with tears of joy', 'cat laugh'],
  ['😻', 'smiling cat with heart eyes', 'cat love'],
  ['😽', 'kissing cat', 'cat kiss'],
  ['🙀', 'weary cat', 'cat shocked'],
  ['😿', 'crying cat', 'cat sad'],
  ['😾', 'pouting cat', 'cat grumpy'],
]

const PEOPLE: EmojiTuple[] = [
  ['👋', 'waving hand', 'hello bye wave'],
  ['🤚', 'raised back of hand', 'hand'],
  ['🖐️', 'hand with fingers splayed', 'hand five'],
  ['✋', 'raised hand', 'stop high five'],
  ['🖖', 'vulcan salute', 'spock'],
  ['👌', 'ok hand', 'ok perfect'],
  ['🤌', 'pinched fingers', 'italian'],
  ['🤏', 'pinching hand', 'small little'],
  ['✌️', 'victory hand', 'peace two'],
  ['🤞', 'crossed fingers', 'luck hopeful'],
  ['🤟', 'love you gesture', 'ily'],
  ['🤘', 'sign of the horns', 'rock'],
  ['🤙', 'call me hand', 'shaka hang loose'],
  ['👈', 'backhand index pointing left', 'point left'],
  ['👉', 'backhand index pointing right', 'point right'],
  ['👆', 'backhand index pointing up', 'point up'],
  ['👇', 'backhand index pointing down', 'point down'],
  ['☝️', 'index pointing up', 'point one'],
  ['👍', 'thumbs up', 'like yes approve ok'],
  ['👎', 'thumbs down', 'dislike no'],
  ['✊', 'raised fist', 'power solidarity'],
  ['👊', 'oncoming fist', 'punch bump'],
  ['🤛', 'left facing fist', 'bump'],
  ['🤜', 'right facing fist', 'bump'],
  ['👏', 'clapping hands', 'applause bravo'],
  ['🙌', 'raising hands', 'celebrate praise hooray'],
  ['👐', 'open hands', 'hug'],
  ['🤲', 'palms up together', 'pray dua'],
  ['🤝', 'handshake', 'deal agreement'],
  ['🙏', 'folded hands', 'please thanks pray'],
  ['✍️', 'writing hand', 'write sign'],
  ['💅', 'nail polish', 'manicure'],
  ['💪', 'flexed biceps', 'strong muscle'],
  ['🦾', 'mechanical arm', 'prosthetic'],
  ['🦵', 'leg', 'kick'],
  ['🦶', 'foot', 'stomp'],
  ['👂', 'ear', 'listen'],
  ['👃', 'nose', 'smell'],
  ['🧠', 'brain', 'smart think'],
  ['🦷', 'tooth', 'dentist'],
  ['👀', 'eyes', 'look see watch'],
  ['👁️', 'eye', 'look'],
  ['👅', 'tongue', 'taste'],
  ['👄', 'mouth', 'lips kiss'],
  ['👶', 'baby', 'infant child'],
  ['🧒', 'child', 'kid'],
  ['👦', 'boy', 'child'],
  ['👧', 'girl', 'child'],
  ['🧑', 'person', 'adult'],
  ['👨', 'man', 'adult'],
  ['👩', 'woman', 'adult'],
  ['🧓', 'older person', 'elderly'],
  ['👴', 'old man', 'elderly grandfather'],
  ['👵', 'old woman', 'elderly grandmother'],
  ['🙍', 'person frowning', 'sad'],
  ['🙎', 'person pouting', 'grumpy'],
  ['🙅', 'person gesturing no', 'no stop'],
  ['🙆', 'person gesturing ok', 'ok yes'],
  ['💁', 'person tipping hand', 'sassy information'],
  ['🙋', 'person raising hand', 'question volunteer'],
  ['🧏', 'deaf person', 'accessibility'],
  ['🙇', 'person bowing', 'sorry respect'],
  ['🤦', 'person facepalming', 'facepalm disbelief'],
  ['🤷', 'person shrugging', 'shrug dunno'],
  ['👮', 'police officer', 'cop'],
  ['🕵️', 'detective', 'spy investigate'],
  ['💂', 'guard', 'soldier'],
  ['👷', 'construction worker', 'builder'],
  ['🤴', 'prince', 'royalty'],
  ['👸', 'princess', 'royalty'],
  ['👳', 'person wearing turban', 'turban'],
  ['🧕', 'woman with headscarf', 'hijab'],
  ['👰', 'person with veil', 'bride wedding'],
  ['🤰', 'pregnant woman', 'pregnancy'],
  ['🎅', 'santa claus', 'christmas'],
  ['🦸', 'superhero', 'hero'],
  ['🦹', 'supervillain', 'villain'],
  ['🧙', 'mage', 'wizard magic'],
  ['🧚', 'fairy', 'magic'],
  ['🧛', 'vampire', 'dracula'],
  ['🧜', 'merperson', 'mermaid'],
  ['🧟', 'zombie', 'undead'],
  ['💆', 'person getting massage', 'spa relax'],
  ['💇', 'person getting haircut', 'salon'],
  ['🚶', 'person walking', 'walk'],
  ['🏃', 'person running', 'run exercise'],
  ['💃', 'woman dancing', 'dance'],
  ['🕺', 'man dancing', 'dance'],
  ['👪', 'family', 'parents children'],
  ['🗣️', 'speaking head', 'talk say'],
  ['👤', 'bust in silhouette', 'user person'],
  ['👥', 'busts in silhouette', 'users group'],
]

const ANIMALS: EmojiTuple[] = [
  ['🐶', 'dog face', 'puppy pet'],
  ['🐱', 'cat face', 'kitten pet'],
  ['🐭', 'mouse face', 'rodent'],
  ['🐹', 'hamster', 'pet'],
  ['🐰', 'rabbit face', 'bunny'],
  ['🦊', 'fox', 'animal'],
  ['🐻', 'bear', 'animal'],
  ['🐼', 'panda', 'bear'],
  ['🐨', 'koala', 'australia'],
  ['🐯', 'tiger face', 'animal'],
  ['🦁', 'lion', 'animal king'],
  ['🐮', 'cow face', 'farm'],
  ['🐷', 'pig face', 'farm'],
  ['🐸', 'frog', 'animal'],
  ['🐵', 'monkey face', 'animal'],
  ['🙈', 'see no evil monkey', 'monkey hide'],
  ['🙉', 'hear no evil monkey', 'monkey'],
  ['🙊', 'speak no evil monkey', 'monkey quiet'],
  ['🐒', 'monkey', 'animal'],
  ['🐔', 'chicken', 'farm'],
  ['🐧', 'penguin', 'bird cold'],
  ['🐦', 'bird', 'animal'],
  ['🐤', 'baby chick', 'bird'],
  ['🦆', 'duck', 'bird'],
  ['🦅', 'eagle', 'bird'],
  ['🦉', 'owl', 'bird night'],
  ['🦇', 'bat', 'halloween'],
  ['🐺', 'wolf', 'animal'],
  ['🐗', 'boar', 'animal'],
  ['🐴', 'horse face', 'animal'],
  ['🦄', 'unicorn', 'magic'],
  ['🐝', 'honeybee', 'bee insect'],
  ['🐛', 'bug', 'insect caterpillar'],
  ['🦋', 'butterfly', 'insect'],
  ['🐌', 'snail', 'slow'],
  ['🐞', 'lady beetle', 'ladybug insect'],
  ['🐜', 'ant', 'insect'],
  ['🕷️', 'spider', 'insect halloween'],
  ['🦂', 'scorpion', 'insect'],
  ['🐢', 'turtle', 'slow'],
  ['🐍', 'snake', 'animal'],
  ['🦎', 'lizard', 'reptile'],
  ['🦖', 't rex', 'dinosaur'],
  ['🐙', 'octopus', 'sea'],
  ['🦑', 'squid', 'sea'],
  ['🦐', 'shrimp', 'sea food'],
  ['🦀', 'crab', 'sea'],
  ['🐡', 'blowfish', 'fish sea'],
  ['🐠', 'tropical fish', 'sea'],
  ['🐟', 'fish', 'sea'],
  ['🐬', 'dolphin', 'sea'],
  ['🐳', 'spouting whale', 'sea'],
  ['🦈', 'shark', 'sea'],
  ['🐊', 'crocodile', 'reptile'],
  ['🐅', 'tiger', 'animal'],
  ['🦓', 'zebra', 'animal'],
  ['🦍', 'gorilla', 'ape'],
  ['🐘', 'elephant', 'animal'],
  ['🦏', 'rhinoceros', 'animal'],
  ['🐪', 'camel', 'desert'],
  ['🦒', 'giraffe', 'animal'],
  ['🐄', 'cow', 'farm'],
  ['🐖', 'pig', 'farm'],
  ['🐑', 'ewe', 'sheep farm'],
  ['🐐', 'goat', 'farm'],
  ['🐕', 'dog', 'pet'],
  ['🐈', 'cat', 'pet'],
  ['🐓', 'rooster', 'farm'],
  ['🦃', 'turkey', 'thanksgiving'],
  ['🕊️', 'dove', 'peace bird'],
  ['🐇', 'rabbit', 'bunny'],
  ['🐿️', 'chipmunk', 'squirrel'],
  ['🦔', 'hedgehog', 'animal'],
  ['🐾', 'paw prints', 'animal tracks'],
  ['🌵', 'cactus', 'plant desert'],
  ['🎄', 'christmas tree', 'holiday'],
  ['🌲', 'evergreen tree', 'forest'],
  ['🌳', 'deciduous tree', 'forest'],
  ['🌴', 'palm tree', 'beach tropical'],
  ['🌱', 'seedling', 'plant grow'],
  ['🌿', 'herb', 'plant leaf'],
  ['☘️', 'shamrock', 'clover irish'],
  ['🍀', 'four leaf clover', 'luck'],
  ['🍁', 'maple leaf', 'autumn canada'],
  ['🍂', 'fallen leaf', 'autumn'],
  ['🍃', 'leaf fluttering in wind', 'wind leaf'],
  ['🌺', 'hibiscus', 'flower'],
  ['🌻', 'sunflower', 'flower'],
  ['🌹', 'rose', 'flower love'],
  ['🥀', 'wilted flower', 'flower sad'],
  ['🌷', 'tulip', 'flower'],
  ['🌸', 'cherry blossom', 'flower sakura'],
  ['💐', 'bouquet', 'flowers gift'],
  ['🍄', 'mushroom', 'fungus'],
  ['🌍', 'globe showing europe africa', 'earth world'],
  ['🌙', 'crescent moon', 'night'],
  ['⭐', 'star', 'night favourite'],
  ['🌟', 'glowing star', 'sparkle'],
  ['☀️', 'sun', 'sunny weather'],
  ['⛅', 'sun behind cloud', 'weather'],
  ['☁️', 'cloud', 'weather'],
  ['🌧️', 'cloud with rain', 'weather rain'],
  ['⛈️', 'cloud with lightning and rain', 'storm'],
  ['❄️', 'snowflake', 'cold winter'],
  ['⛄', 'snowman without snow', 'winter'],
  ['🔥', 'fire', 'hot lit flame'],
  ['💧', 'droplet', 'water'],
  ['🌊', 'water wave', 'sea ocean'],
  ['🌈', 'rainbow', 'pride weather'],
]

const FOOD: EmojiTuple[] = [
  ['🍏', 'green apple', 'fruit'],
  ['🍎', 'red apple', 'fruit'],
  ['🍐', 'pear', 'fruit'],
  ['🍊', 'tangerine', 'orange fruit'],
  ['🍋', 'lemon', 'fruit sour'],
  ['🍌', 'banana', 'fruit'],
  ['🍉', 'watermelon', 'fruit summer'],
  ['🍇', 'grapes', 'fruit'],
  ['🍓', 'strawberry', 'fruit'],
  ['🫐', 'blueberries', 'fruit'],
  ['🍈', 'melon', 'fruit'],
  ['🍒', 'cherries', 'fruit'],
  ['🍑', 'peach', 'fruit'],
  ['🥭', 'mango', 'fruit tropical'],
  ['🍍', 'pineapple', 'fruit tropical'],
  ['🥥', 'coconut', 'fruit tropical'],
  ['🥝', 'kiwi fruit', 'fruit'],
  ['🍅', 'tomato', 'vegetable'],
  ['🍆', 'eggplant', 'aubergine vegetable'],
  ['🥑', 'avocado', 'fruit'],
  ['🥦', 'broccoli', 'vegetable'],
  ['🥬', 'leafy green', 'vegetable salad'],
  ['🥒', 'cucumber', 'vegetable'],
  ['🌶️', 'hot pepper', 'spicy chilli'],
  ['🌽', 'ear of corn', 'vegetable'],
  ['🥕', 'carrot', 'vegetable'],
  ['🧄', 'garlic', 'vegetable'],
  ['🧅', 'onion', 'vegetable'],
  ['🥔', 'potato', 'vegetable'],
  ['🍠', 'roasted sweet potato', 'vegetable'],
  ['🥐', 'croissant', 'bread breakfast'],
  ['🥯', 'bagel', 'bread'],
  ['🍞', 'bread', 'loaf'],
  ['🥖', 'baguette bread', 'french bread'],
  ['🧀', 'cheese wedge', 'cheese'],
  ['🥚', 'egg', 'breakfast'],
  ['🍳', 'cooking', 'egg fried breakfast'],
  ['🧈', 'butter', 'dairy'],
  ['🥞', 'pancakes', 'breakfast'],
  ['🧇', 'waffle', 'breakfast'],
  ['🥓', 'bacon', 'breakfast meat'],
  ['🍔', 'hamburger', 'burger fast food'],
  ['🍟', 'french fries', 'chips fast food'],
  ['🍕', 'pizza', 'slice'],
  ['🌭', 'hot dog', 'fast food'],
  ['🥪', 'sandwich', 'lunch'],
  ['🌮', 'taco', 'mexican'],
  ['🌯', 'burrito', 'mexican wrap'],
  ['🥙', 'stuffed flatbread', 'kebab shawarma'],
  ['🧆', 'falafel', 'middle eastern'],
  ['🥗', 'green salad', 'healthy'],
  ['🥘', 'shallow pan of food', 'paella cooking'],
  ['🍝', 'spaghetti', 'pasta italian'],
  ['🍜', 'steaming bowl', 'ramen noodles'],
  ['🍲', 'pot of food', 'stew soup'],
  ['🍛', 'curry rice', 'curry'],
  ['🍣', 'sushi', 'japanese'],
  ['🍤', 'fried shrimp', 'tempura'],
  ['🍚', 'cooked rice', 'rice'],
  ['🥟', 'dumpling', 'gyoza'],
  ['🍿', 'popcorn', 'cinema snack'],
  ['🧂', 'salt', 'seasoning'],
  ['🥫', 'canned food', 'tin'],
  ['🍦', 'soft ice cream', 'dessert'],
  ['🍩', 'doughnut', 'donut dessert'],
  ['🍪', 'cookie', 'biscuit dessert'],
  ['🎂', 'birthday cake', 'birthday celebrate'],
  ['🍰', 'shortcake', 'cake dessert'],
  ['🧁', 'cupcake', 'dessert'],
  ['🥧', 'pie', 'dessert'],
  ['🍫', 'chocolate bar', 'sweet'],
  ['🍬', 'candy', 'sweet'],
  ['🍭', 'lollipop', 'sweet'],
  ['🍯', 'honey pot', 'honey sweet'],
  ['🍼', 'baby bottle', 'milk baby'],
  ['🥛', 'glass of milk', 'dairy'],
  ['☕', 'hot beverage', 'coffee tea'],
  ['🫖', 'teapot', 'tea'],
  ['🍵', 'teacup without handle', 'green tea'],
  ['🧃', 'beverage box', 'juice'],
  ['🥤', 'cup with straw', 'soda drink'],
  ['🧋', 'bubble tea', 'boba'],
  ['🍺', 'beer mug', 'beer drink'],
  ['🍻', 'clinking beer mugs', 'cheers beer'],
  ['🥂', 'clinking glasses', 'cheers celebrate'],
  ['🍷', 'wine glass', 'wine'],
  ['🥃', 'tumbler glass', 'whisky'],
  ['🍸', 'cocktail glass', 'martini'],
  ['🍹', 'tropical drink', 'cocktail'],
  ['🧊', 'ice', 'cold cube'],
  ['🍽️', 'fork and knife with plate', 'dinner eat'],
  ['🥄', 'spoon', 'cutlery'],
]

const ACTIVITY: EmojiTuple[] = [
  ['⚽', 'soccer ball', 'football sport'],
  ['🏀', 'basketball', 'sport'],
  ['🏈', 'american football', 'sport'],
  ['⚾', 'baseball', 'sport'],
  ['🥎', 'softball', 'sport'],
  ['🎾', 'tennis', 'sport'],
  ['🏐', 'volleyball', 'sport'],
  ['🏉', 'rugby football', 'sport'],
  ['🥏', 'flying disc', 'frisbee'],
  ['🎱', 'pool 8 ball', 'billiards'],
  ['🏓', 'ping pong', 'table tennis'],
  ['🏸', 'badminton', 'sport'],
  ['🥅', 'goal net', 'sport'],
  ['🏒', 'ice hockey', 'sport'],
  ['🏑', 'field hockey', 'sport'],
  ['🥍', 'lacrosse', 'sport'],
  ['🏏', 'cricket game', 'sport'],
  ['🥊', 'boxing glove', 'boxing sport'],
  ['🥋', 'martial arts uniform', 'judo karate'],
  ['⛳', 'flag in hole', 'golf'],
  ['⛸️', 'ice skate', 'skating'],
  ['🎣', 'fishing pole', 'fishing'],
  ['🤿', 'diving mask', 'diving snorkel'],
  ['🎽', 'running shirt', 'marathon'],
  ['🎿', 'skis', 'skiing winter'],
  ['🛷', 'sled', 'winter'],
  ['🥌', 'curling stone', 'winter sport'],
  ['🏆', 'trophy', 'win award champion'],
  ['🥇', 'first place medal', 'gold win'],
  ['🥈', 'second place medal', 'silver'],
  ['🥉', 'third place medal', 'bronze'],
  ['🏅', 'sports medal', 'award'],
  ['🎖️', 'military medal', 'award'],
  ['🎯', 'bullseye', 'target darts goal'],
  ['🎮', 'video game', 'gaming controller'],
  ['🕹️', 'joystick', 'gaming'],
  ['🎲', 'game die', 'dice random'],
  ['♟️', 'chess pawn', 'chess'],
  ['🧩', 'puzzle piece', 'jigsaw'],
  ['🎰', 'slot machine', 'gambling'],
  ['🎳', 'bowling', 'sport'],
  ['🎪', 'circus tent', 'circus'],
  ['🎭', 'performing arts', 'theatre drama'],
  ['🎨', 'artist palette', 'art paint'],
  ['🎤', 'microphone', 'sing karaoke'],
  ['🎧', 'headphone', 'music listen'],
  ['🎼', 'musical score', 'music'],
  ['🎵', 'musical note', 'music'],
  ['🎶', 'musical notes', 'music'],
  ['🎹', 'musical keyboard', 'piano'],
  ['🥁', 'drum', 'music'],
  ['🎷', 'saxophone', 'music jazz'],
  ['🎺', 'trumpet', 'music'],
  ['🎸', 'guitar', 'music rock'],
  ['🎻', 'violin', 'music'],
  ['🎬', 'clapper board', 'film movie'],
  ['🎫', 'ticket', 'event'],
  ['🎗️', 'reminder ribbon', 'awareness'],
  ['🎉', 'party popper', 'celebrate congrats'],
  ['🎊', 'confetti ball', 'celebrate party'],
  ['🎈', 'balloon', 'party birthday'],
  ['🎁', 'wrapped gift', 'present birthday'],
  ['🎃', 'jack o lantern', 'halloween pumpkin'],
  ['🧨', 'firecracker', 'fireworks'],
  ['✨', 'sparkles', 'shiny clean magic'],
  ['🎇', 'sparkler', 'fireworks'],
  ['🎆', 'fireworks', 'celebrate'],
]

const TRAVEL: EmojiTuple[] = [
  ['🚗', 'automobile', 'car drive'],
  ['🚕', 'taxi', 'cab'],
  ['🚙', 'sport utility vehicle', 'suv car'],
  ['🚌', 'bus', 'transport'],
  ['🚎', 'trolleybus', 'transport'],
  ['🏎️', 'racing car', 'formula one'],
  ['🚓', 'police car', 'police'],
  ['🚑', 'ambulance', 'emergency'],
  ['🚒', 'fire engine', 'emergency'],
  ['🚐', 'minibus', 'van'],
  ['🚚', 'delivery truck', 'shipping'],
  ['🚛', 'articulated lorry', 'truck'],
  ['🚜', 'tractor', 'farm'],
  ['🛵', 'motor scooter', 'vespa'],
  ['🏍️', 'motorcycle', 'bike'],
  ['🚲', 'bicycle', 'bike cycling'],
  ['🛴', 'kick scooter', 'scooter'],
  ['🚨', 'police car light', 'siren emergency'],
  ['🚔', 'oncoming police car', 'police'],
  ['🚍', 'oncoming bus', 'transport'],
  ['🚖', 'oncoming taxi', 'cab'],
  ['🚡', 'aerial tramway', 'cable car'],
  ['🚠', 'mountain cableway', 'cable car'],
  ['🚟', 'suspension railway', 'transport'],
  ['🚃', 'railway car', 'train'],
  ['🚋', 'tram car', 'tram'],
  ['🚞', 'mountain railway', 'train'],
  ['🚝', 'monorail', 'train'],
  ['🚄', 'high speed train', 'bullet train'],
  ['🚅', 'bullet train', 'shinkansen'],
  ['🚈', 'light rail', 'train'],
  ['🚂', 'locomotive', 'steam train'],
  ['🚆', 'train', 'transport'],
  ['🚇', 'metro', 'subway underground'],
  ['🚊', 'tram', 'transport'],
  ['🚉', 'station', 'train'],
  ['✈️', 'airplane', 'flight travel'],
  ['🛫', 'airplane departure', 'takeoff'],
  ['🛬', 'airplane arrival', 'landing'],
  ['🛩️', 'small airplane', 'flight'],
  ['💺', 'seat', 'flight'],
  ['🚁', 'helicopter', 'flight'],
  ['🚀', 'rocket', 'launch space startup'],
  ['🛸', 'flying saucer', 'ufo alien'],
  ['⛵', 'sailboat', 'sailing sea'],
  ['🚤', 'speedboat', 'boat'],
  ['🛥️', 'motor boat', 'boat'],
  ['🛳️', 'passenger ship', 'cruise'],
  ['⚓', 'anchor', 'ship'],
  ['⛽', 'fuel pump', 'petrol gas'],
  ['🚧', 'construction', 'roadworks'],
  ['🚦', 'vertical traffic light', 'traffic'],
  ['🚥', 'horizontal traffic light', 'traffic'],
  ['🗺️', 'world map', 'travel'],
  ['🗿', 'moai', 'statue'],
  ['🗽', 'statue of liberty', 'new york'],
  ['🗼', 'tokyo tower', 'japan'],
  ['🏰', 'castle', 'fairytale'],
  ['🏯', 'japanese castle', 'japan'],
  ['🏟️', 'stadium', 'sport'],
  ['🎡', 'ferris wheel', 'fair'],
  ['🎢', 'roller coaster', 'theme park'],
  ['🎠', 'carousel horse', 'fair'],
  ['⛲', 'fountain', 'park'],
  ['⛱️', 'umbrella on ground', 'beach'],
  ['🏖️', 'beach with umbrella', 'holiday'],
  ['🏝️', 'desert island', 'holiday'],
  ['🏔️', 'snow capped mountain', 'mountain'],
  ['⛰️', 'mountain', 'hiking'],
  ['🌋', 'volcano', 'eruption'],
  ['🏕️', 'camping', 'tent outdoors'],
  ['🏠', 'house', 'home'],
  ['🏡', 'house with garden', 'home'],
  ['🏢', 'office building', 'work'],
  ['🏥', 'hospital', 'health'],
  ['🏦', 'bank', 'money'],
  ['🏨', 'hotel', 'travel'],
  ['🏪', 'convenience store', 'shop'],
  ['🏫', 'school', 'education'],
  ['🕌', 'mosque', 'islam'],
  ['🕍', 'synagogue', 'judaism'],
  ['⛪', 'church', 'christianity'],
  ['🕋', 'kaaba', 'mecca islam'],
  ['🌃', 'night with stars', 'city night'],
  ['🌆', 'cityscape at dusk', 'city'],
  ['🌇', 'sunset', 'city evening'],
  ['🌉', 'bridge at night', 'city'],
  ['🎑', 'moon viewing ceremony', 'japan'],
]

const OBJECTS: EmojiTuple[] = [
  ['⌚', 'watch', 'time'],
  ['📱', 'mobile phone', 'smartphone'],
  ['💻', 'laptop', 'computer work'],
  ['⌨️', 'keyboard', 'typing'],
  ['🖥️', 'desktop computer', 'pc'],
  ['🖨️', 'printer', 'print'],
  ['🖱️', 'computer mouse', 'click'],
  ['💽', 'computer disk', 'storage'],
  ['💾', 'floppy disk', 'save'],
  ['💿', 'optical disk', 'cd'],
  ['📀', 'dvd', 'disc'],
  ['📷', 'camera', 'photo'],
  ['📸', 'camera with flash', 'photo'],
  ['📹', 'video camera', 'record'],
  ['🎥', 'movie camera', 'film'],
  ['📞', 'telephone receiver', 'call phone'],
  ['☎️', 'telephone', 'call'],
  ['📟', 'pager', 'beeper'],
  ['📠', 'fax machine', 'fax'],
  ['📺', 'television', 'tv'],
  ['📻', 'radio', 'music'],
  ['🔋', 'battery', 'power'],
  ['🔌', 'electric plug', 'power'],
  ['💡', 'light bulb', 'idea'],
  ['🔦', 'flashlight', 'torch'],
  ['🕯️', 'candle', 'light'],
  ['🧯', 'fire extinguisher', 'safety'],
  ['🛢️', 'oil drum', 'barrel'],
  ['💸', 'money with wings', 'spending'],
  ['💵', 'dollar banknote', 'money cash'],
  ['💴', 'yen banknote', 'money'],
  ['💶', 'euro banknote', 'money'],
  ['💷', 'pound banknote', 'money'],
  ['💰', 'money bag', 'money rich'],
  ['💳', 'credit card', 'payment'],
  ['🧾', 'receipt', 'invoice bill'],
  ['💎', 'gem stone', 'diamond'],
  ['⚖️', 'balance scale', 'justice legal'],
  ['🧰', 'toolbox', 'tools'],
  ['🔧', 'wrench', 'tool fix'],
  ['🔨', 'hammer', 'tool build'],
  ['🪛', 'screwdriver', 'tool'],
  ['🔩', 'nut and bolt', 'tool'],
  ['⚙️', 'gear', 'settings cog'],
  ['🧲', 'magnet', 'attract'],
  ['🔫', 'water pistol', 'gun toy'],
  ['💣', 'bomb', 'explosive'],
  ['🔪', 'kitchen knife', 'cut'],
  ['🗡️', 'dagger', 'blade'],
  ['🛡️', 'shield', 'protection security'],
  ['🚬', 'cigarette', 'smoking'],
  ['⚰️', 'coffin', 'death'],
  ['🔮', 'crystal ball', 'fortune magic'],
  ['📿', 'prayer beads', 'religion'],
  ['💈', 'barber pole', 'haircut'],
  ['🔭', 'telescope', 'space'],
  ['🔬', 'microscope', 'science lab'],
  ['🧪', 'test tube', 'science'],
  ['🧬', 'dna', 'biology'],
  ['💊', 'pill', 'medicine'],
  ['💉', 'syringe', 'vaccine injection'],
  ['🩹', 'adhesive bandage', 'plaster'],
  ['🩺', 'stethoscope', 'doctor'],
  ['🚪', 'door', 'entry'],
  ['🪑', 'chair', 'seat'],
  ['🛏️', 'bed', 'sleep'],
  ['🚿', 'shower', 'bathroom'],
  ['🛁', 'bathtub', 'bathroom'],
  ['🧴', 'lotion bottle', 'soap'],
  ['🧼', 'soap', 'wash'],
  ['🧹', 'broom', 'clean'],
  ['🧺', 'basket', 'laundry'],
  ['🔑', 'key', 'unlock'],
  ['🔒', 'locked', 'secure privacy'],
  ['🔓', 'unlocked', 'open'],
  ['🔔', 'bell', 'notification alert'],
  ['🔕', 'bell with slash', 'mute silence'],
  ['📢', 'loudspeaker', 'announcement'],
  ['📣', 'megaphone', 'shout'],
  ['📯', 'postal horn', 'announce'],
  ['📌', 'pushpin', 'pin location'],
  ['📎', 'paperclip', 'attachment'],
  ['✂️', 'scissors', 'cut'],
  ['📝', 'memo', 'note write'],
  ['✏️', 'pencil', 'write edit'],
  ['🖊️', 'pen', 'write'],
  ['📖', 'open book', 'read'],
  ['📚', 'books', 'library read'],
  ['📓', 'notebook', 'notes'],
  ['📋', 'clipboard', 'list'],
  ['📅', 'calendar', 'date schedule'],
  ['📆', 'tear off calendar', 'date'],
  ['🗓️', 'spiral calendar', 'schedule'],
  ['📈', 'chart increasing', 'growth stats'],
  ['📉', 'chart decreasing', 'loss stats'],
  ['📊', 'bar chart', 'stats analytics'],
  ['🗂️', 'card index dividers', 'files'],
  ['📁', 'file folder', 'folder'],
  ['📂', 'open file folder', 'folder'],
  ['🗃️', 'card file box', 'archive'],
  ['🗄️', 'file cabinet', 'archive'],
  ['🗑️', 'wastebasket', 'delete trash'],
  ['📦', 'package', 'box shipping'],
  ['📫', 'closed mailbox with raised flag', 'mail'],
  ['📮', 'postbox', 'mail'],
  ['✉️', 'envelope', 'email mail'],
  ['📧', 'e mail', 'email'],
  ['📨', 'incoming envelope', 'mail'],
  ['📤', 'outbox tray', 'send'],
  ['📥', 'inbox tray', 'receive'],
  ['🔍', 'magnifying glass tilted left', 'search find'],
  ['🔎', 'magnifying glass tilted right', 'search'],
  ['👑', 'crown', 'king queen vip'],
  ['👓', 'glasses', 'eyewear'],
  ['🕶️', 'sunglasses', 'cool'],
  ['👔', 'necktie', 'formal work'],
  ['👕', 't shirt', 'clothes'],
  ['👖', 'jeans', 'clothes'],
  ['👗', 'dress', 'clothes'],
  ['👜', 'handbag', 'bag'],
  ['🎒', 'backpack', 'school bag'],
  ['👟', 'running shoe', 'sneaker'],
  ['👞', 'mans shoe', 'shoe'],
  ['🧦', 'socks', 'clothes'],
  ['🧢', 'billed cap', 'hat'],
  ['🎩', 'top hat', 'formal'],
]

const SYMBOLS: EmojiTuple[] = [
  ['❤️', 'red heart', 'love like'],
  ['🧡', 'orange heart', 'love'],
  ['💛', 'yellow heart', 'love'],
  ['💚', 'green heart', 'love'],
  ['💙', 'blue heart', 'love'],
  ['💜', 'purple heart', 'love'],
  ['🖤', 'black heart', 'love'],
  ['🤍', 'white heart', 'love'],
  ['🤎', 'brown heart', 'love'],
  ['💔', 'broken heart', 'breakup sad'],
  ['❣️', 'heart exclamation', 'love'],
  ['💕', 'two hearts', 'love'],
  ['💞', 'revolving hearts', 'love'],
  ['💓', 'beating heart', 'love'],
  ['💗', 'growing heart', 'love'],
  ['💖', 'sparkling heart', 'love'],
  ['💘', 'heart with arrow', 'cupid love'],
  ['💝', 'heart with ribbon', 'gift love'],
  ['💟', 'heart decoration', 'love'],
  ['☮️', 'peace symbol', 'peace'],
  ['✝️', 'latin cross', 'christianity'],
  ['☪️', 'star and crescent', 'islam'],
  ['🕉️', 'om', 'hinduism'],
  ['☸️', 'wheel of dharma', 'buddhism'],
  ['✡️', 'star of david', 'judaism'],
  ['☯️', 'yin yang', 'balance'],
  ['♈', 'aries', 'zodiac'],
  ['♉', 'taurus', 'zodiac'],
  ['♊', 'gemini', 'zodiac'],
  ['♋', 'cancer', 'zodiac'],
  ['♌', 'leo', 'zodiac'],
  ['♍', 'virgo', 'zodiac'],
  ['♎', 'libra', 'zodiac'],
  ['♏', 'scorpio', 'zodiac'],
  ['♐', 'sagittarius', 'zodiac'],
  ['♑', 'capricorn', 'zodiac'],
  ['♒', 'aquarius', 'zodiac'],
  ['♓', 'pisces', 'zodiac'],
  ['🆔', 'id button', 'identity'],
  ['⚛️', 'atom symbol', 'science'],
  ['✅', 'check mark button', 'done yes tick'],
  ['☑️', 'check box with check', 'done'],
  ['✔️', 'check mark', 'tick done'],
  ['❌', 'cross mark', 'no wrong cancel'],
  ['❎', 'cross mark button', 'no'],
  ['➕', 'plus', 'add'],
  ['➖', 'minus', 'subtract'],
  ['➗', 'divide', 'division'],
  ['✖️', 'multiply', 'times'],
  ['♾️', 'infinity', 'forever'],
  ['‼️', 'double exclamation mark', 'important'],
  ['⁉️', 'exclamation question mark', 'surprise'],
  ['❓', 'question mark', 'help ask'],
  ['❔', 'white question mark', 'ask'],
  ['❕', 'white exclamation mark', 'important'],
  ['❗', 'exclamation mark', 'important warning'],
  ['〰️', 'wavy dash', 'squiggle'],
  ['⚠️', 'warning', 'caution alert'],
  ['🚫', 'prohibited', 'no forbidden'],
  ['⛔', 'no entry', 'stop'],
  ['♻️', 'recycling symbol', 'recycle green'],
  ['🔱', 'trident emblem', 'symbol'],
  ['⚜️', 'fleur de lis', 'symbol'],
  ['🔰', 'japanese symbol for beginner', 'novice'],
  ['⭕', 'hollow red circle', 'circle correct'],
  ['🆗', 'ok button', 'ok'],
  ['🆕', 'new button', 'new'],
  ['🆓', 'free button', 'free'],
  ['🆙', 'up button', 'up'],
  ['🔝', 'top arrow', 'top'],
  ['🔜', 'soon arrow', 'soon'],
  ['🔙', 'back arrow', 'back'],
  ['⬆️', 'up arrow', 'up'],
  ['⬇️', 'down arrow', 'down'],
  ['⬅️', 'left arrow', 'left'],
  ['➡️', 'right arrow', 'right'],
  ['↩️', 'right arrow curving left', 'reply back'],
  ['🔄', 'counterclockwise arrows', 'refresh sync'],
  ['🔃', 'clockwise vertical arrows', 'reload'],
  ['🔁', 'repeat', 'loop'],
  ['🔂', 'repeat single', 'loop one'],
  ['▶️', 'play button', 'play'],
  ['⏸️', 'pause button', 'pause'],
  ['⏹️', 'stop button', 'stop'],
  ['⏺️', 'record button', 'record'],
  ['⏭️', 'next track button', 'skip'],
  ['⏮️', 'last track button', 'previous'],
  ['🔀', 'shuffle tracks button', 'shuffle random'],
  ['🔊', 'speaker high volume', 'loud sound'],
  ['🔇', 'muted speaker', 'mute silent'],
  ['📶', 'antenna bars', 'signal'],
  ['📳', 'vibration mode', 'vibrate'],
  ['♿', 'wheelchair symbol', 'accessibility'],
  ['🚻', 'restroom', 'toilet'],
  ['🅿️', 'p button', 'parking'],
  ['🈚', 'japanese free of charge button', 'free'],
  ['💯', 'hundred points', 'perfect score'],
  ['🔢', 'input numbers', 'numbers'],
  ['💤', 'zzz', 'sleep'],
  ['🕐', 'one oclock', 'time clock'],
  ['⏰', 'alarm clock', 'time alarm'],
  ['⏳', 'hourglass not done', 'wait time'],
  ['⌛', 'hourglass done', 'time up'],
  ['🔴', 'red circle', 'circle'],
  ['🟠', 'orange circle', 'circle'],
  ['🟡', 'yellow circle', 'circle'],
  ['🟢', 'green circle', 'circle online'],
  ['🔵', 'blue circle', 'circle'],
  ['🟣', 'purple circle', 'circle'],
  ['⚫', 'black circle', 'circle'],
  ['⚪', 'white circle', 'circle'],
  ['🟥', 'red square', 'square'],
  ['🟩', 'green square', 'square'],
  ['🟦', 'blue square', 'square'],
  ['⬛', 'black large square', 'square'],
  ['⬜', 'white large square', 'square'],
]

const FLAGS: EmojiTuple[] = [
  ['🏳️', 'white flag', 'surrender'],
  ['🏴', 'black flag', 'flag'],
  ['🏁', 'chequered flag', 'race finish'],
  ['🚩', 'triangular flag', 'red flag'],
  ['🏳️‍🌈', 'rainbow flag', 'pride lgbt'],
  ['🇦🇪', 'flag united arab emirates', 'uae'],
  ['🇦🇷', 'flag argentina', 'argentina'],
  ['🇦🇺', 'flag australia', 'australia'],
  ['🇧🇪', 'flag belgium', 'belgium'],
  ['🇧🇭', 'flag bahrain', 'bahrain'],
  ['🇧🇷', 'flag brazil', 'brazil'],
  ['🇨🇦', 'flag canada', 'canada'],
  ['🇨🇭', 'flag switzerland', 'switzerland'],
  ['🇨🇳', 'flag china', 'china'],
  ['🇩🇪', 'flag germany', 'germany'],
  ['🇩🇰', 'flag denmark', 'denmark'],
  ['🇪🇬', 'flag egypt', 'egypt'],
  ['🇪🇸', 'flag spain', 'spain'],
  ['🇫🇷', 'flag france', 'france'],
  ['🇬🇧', 'flag united kingdom', 'uk britain'],
  ['🇬🇷', 'flag greece', 'greece'],
  ['🇮🇩', 'flag indonesia', 'indonesia'],
  ['🇮🇪', 'flag ireland', 'ireland'],
  ['🇮🇳', 'flag india', 'india'],
  ['🇮🇹', 'flag italy', 'italy'],
  ['🇯🇵', 'flag japan', 'japan'],
  ['🇰🇷', 'flag south korea', 'korea'],
  ['🇰🇼', 'flag kuwait', 'kuwait'],
  ['🇲🇽', 'flag mexico', 'mexico'],
  ['🇲🇾', 'flag malaysia', 'malaysia'],
  ['🇳🇬', 'flag nigeria', 'nigeria'],
  ['🇳🇱', 'flag netherlands', 'netherlands'],
  ['🇳🇴', 'flag norway', 'norway'],
  ['🇴🇲', 'flag oman', 'oman'],
  ['🇵🇭', 'flag philippines', 'philippines'],
  ['🇵🇰', 'flag pakistan', 'pakistan'],
  ['🇵🇱', 'flag poland', 'poland'],
  ['🇵🇹', 'flag portugal', 'portugal'],
  ['🇶🇦', 'flag qatar', 'qatar'],
  ['🇷🇺', 'flag russia', 'russia'],
  ['🇸🇦', 'flag saudi arabia', 'saudi'],
  ['🇸🇪', 'flag sweden', 'sweden'],
  ['🇸🇬', 'flag singapore', 'singapore'],
  ['🇹🇷', 'flag turkey', 'turkey'],
  ['🇺🇸', 'flag united states', 'usa america'],
  ['🇿🇦', 'flag south africa', 'south africa'],
]

const GROUPED: [Exclude<WhatsAppEmojiGroupId, 'recent'>, EmojiTuple[]][] = [
  ['smileys', SMILEYS],
  ['people', PEOPLE],
  ['animals', ANIMALS],
  ['food', FOOD],
  ['activity', ACTIVITY],
  ['travel', TRAVEL],
  ['objects', OBJECTS],
  ['symbols', SYMBOLS],
  ['flags', FLAGS],
]

/** The full dataset, in the order the picker renders it. */
export const WHATSAPP_EMOJIS: WhatsAppEmoji[] = GROUPED.flatMap(([group, entries]) =>
  entries.map(([emoji, name, keywords]) => ({
    emoji,
    name,
    keywords: keywords ? keywords.split(' ') : [],
    group,
  })),
)

/** Lookup by character, used to resolve recently-used emoji back to full entries. */
export const WHATSAPP_EMOJIS_BY_CHAR: ReadonlyMap<string, WhatsAppEmoji> = new Map(
  WHATSAPP_EMOJIS.map((entry) => [entry.emoji, entry]),
)

/** Group ids in the order the tab strip shows them, `recent` excluded. */
export const WHATSAPP_EMOJI_GROUP_ORDER = GROUPED.map(([group]) => group)
